project:
  type: website
  output-dir: _site

website:
  title: "The Innovation Crucible"
  description: "Exploring the intersection of AI and Material Science"
  favicon: "media/logo/log05-min-black-0.png"
  
  navbar:
    logo: "media/logo/log05-min-black-0.png"
    logo-alt: "The Innovation Crucible Logo"
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts/index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/iAli61
      - icon: linkedin
        href: https://linkedin.com/in/ali-bina
      - icon: envelope
        href: mailto:ali.bina1361@gmail.com

  sidebar:
    style: "floating"
    
  page-footer:
    left: |
      © 2025 The Innovation Crucible. All rights reserved.
    right: |
      Built with [Quarto](https://quarto.org/)
    background: light

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - styles.css
      - about-page-fix.css
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    code-copy: true
    mainfont: "Inter"
    fontsize: 1.1em
    linestretch: 1.7
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
          <meta name="keywords" content="AI, Machine Learning, Materials Science, LLM, Scientific Computing">
          <meta name="author" content="Ali Bina (PhD)">

execute:
  freeze: auto
