# Introduction

Welcome to Part 2 of our comprehensive torch.compile() series! Building on the fundamentals from Part 1, we now dive deep into advanced debugging techniques, Triton kernel analysis, and systematic optimization strategies.

## **What You'll Master in Part 2**

### 🛠️ **Chapter 2: Advanced Debugging & Optimization**
1. **[Advanced Debugging Toolkit](#debugging-toolkit)** - Environment variables and introspection tools
2. **[Triton Kernel Exploration](#kernel-exploration)** - Examining and understanding generated kernels
3. **[Performance Benchmarking](#performance-benchmarking)** - Systematic optimization analysis

---

## **Advanced Learning Outcomes**

Upon completing Part 2, you will master:

### **Expert-Level Skills**
- **Advanced Debugging**: Expert-level troubleshooting using environment variables
- **Kernel Understanding**: Ability to read and analyze generated Triton GPU kernels
- **Performance Engineering**: Systematic approaches to measuring and optimizing performance
- **Optimization Strategies**: Know when and how to apply compilation for maximum benefit

---

## 🔧 **Prerequisites**

Before proceeding, ensure you've completed **Part 1: Compilation Fundamentals** and understand:

- ✅ The 6-stage compilation pipeline
- ✅ Basic performance analysis techniques
- ✅ Environment variable configuration
- ✅ Break-even analysis concepts

Let's begin with advanced debugging techniques!

## 🚀 Setting Up Your Learning Environment

Before we dive into the advanced concepts, we need to set up a proper learning environment that will allow us to observe and understand the torch.compile() process in detail.

### What This Cell Does:
- **Checks your PyTorch installation** and ensures CUDA/GPU availability
- **Verifies Triton availability** for GPU kernel optimization
- **Configures environment variables** to make the compilation process visible
- **Sets up educational debugging** so you can see what happens under the hood

### Key Environment Variables We'll Use:
- `TORCH_LOGS=output_code`: Shows the actual generated Triton kernel source code
- `TRITON_PRINT_AUTOTUNING=1`: Displays the autotuning process that optimizes kernel parameters
- `TRITON_PRINT_CACHE_STATS=1`: Shows kernel caching statistics for understanding reuse patterns

This setup is crucial for learning because it transforms the usually invisible compilation process into something you can observe and understand step by step.

In [3]:
# Part 1: Environment Setup and Foundation
import os
import torch
import time
import gc
from pathlib import Path
from typing import Dict, List, Tuple
import torch.nn as nn
import torch.nn.functional as F
import glob
import warnings
import torch._dynamo.config as config

print("🚀 PyTorch + Triton Learning Environment Setup")
print("=" * 50)

# Step 1: Check PyTorch and device availability
print(f"📦 PyTorch version: {torch.__version__}")

if torch.cuda.is_available():
    device = "cuda"
    print(f"✅ CUDA GPU available: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
    print(f"   Compute capability: {torch.cuda.get_device_capability(0)}")
    
    # Check Triton availability
    try:
        import triton
        print(f"✅ Triton available: {triton.__version__}")
    except ImportError:
        print(f"⚠️  Triton not available - install with: pip install triton")
        
else:
    device = "cpu"
    print("⚠️  CUDA not available - using CPU")
    print("   Note: Many optimizations are GPU-specific")

print(f"\n🎯 Selected device: {device.upper()}")

# Step 2: Configure environment for educational exploration
def setup_educational_environment():
    """Configure environment variables to see what PyTorch compilation does"""
    
    print(f"\n🔬 Configuring Educational Environment Variables")
    print("   These variables will help us see what happens during compilation:")
    
    educational_config = {
        # Show generated kernel code - the actual Triton kernels
        "TORCH_LOGS": "output_code",
        
        # Display autotuning process - see optimization decisions
        "TRITON_PRINT_AUTOTUNING": "1", 
        
        # Show cache statistics - understand kernel reuse
        "TRITON_PRINT_CACHE_STATS": "1",
    }
    
    for key, value in educational_config.items():
        os.environ[key] = value
        print(f"   ✅ {key} = '{value}'")
    
    print(f"\n💡 What these reveal:")
    print(f"   • output_code: Shows actual generated Triton kernel source code")
    print(f"   • autotuning: Displays optimization decisions being made")  
    print(f"   • cache_stats: Shows when kernels are reused vs regenerated")
    
    return educational_config

# Apply educational configuration
settings = setup_educational_environment()

print(f"\n✅ Environment ready for learning!")
print(f"   We'll now be able to see the internals of PyTorch compilation")

🚀 PyTorch + Triton Learning Environment Setup
📦 PyTorch version: 2.7.1+cu126
✅ CUDA GPU available: NVIDIA GeForce RTX 4050 Laptop GPU
   Memory: 6.0 GB
   Compute capability: (8, 9)
✅ Triton available: 3.3.1

🎯 Selected device: CUDA

🔬 Configuring Educational Environment Variables
   These variables will help us see what happens during compilation:
   ✅ TORCH_LOGS = 'output_code'
   ✅ TRITON_PRINT_AUTOTUNING = '1'
   ✅ TRITON_PRINT_CACHE_STATS = '1'

💡 What these reveal:
   • output_code: Shows actual generated Triton kernel source code
   • autotuning: Displays optimization decisions being made
   • cache_stats: Shows when kernels are reused vs regenerated

✅ Environment ready for learning!
   We'll now be able to see the internals of PyTorch compilation


# Debugging Toolkit: Jupyter-Focused PyTorch Debugging {#debugging-toolkit}


## Debugging Toolkit: Environment Variables & Introspection

Environment variables are your primary tools for understanding torch.compile() internals. They provide unprecedented visibility into the compilation process, from graph capture to kernel generation.

### 🔍 Essential Environment Variables for Advanced Users

| Variable | Purpose | Insight Level | When to Use |
|----------|---------|---------------|-------------|
| `TORCH_LOGS=output_code` | Shows generated Triton kernel source | **Expert** | Understanding optimizations |
| `TRITON_PRINT_AUTOTUNING=1` | Displays autotuning decisions | **Advanced** | Performance debugging |
| `TRITON_PRINT_CACHE_STATS=1` | Cache hit/miss statistics | **Intermediate** | Cache optimization |
| `TORCH_COMPILE_DEBUG=1` | Comprehensive compilation tracing | **Expert** | Deep debugging |
| `TORCHINDUCTOR_VERBOSE=1` | Backend compilation details | **Advanced** | Backend debugging |

### Advanced Debugging Strategies

#### **Level 1: Basic Monitoring** 
- Monitor compilation success/failure
- Track basic performance metrics
- Verify kernel caching behavior

#### **Level 2: Performance Analysis** 
- Analyze autotuning decisions
- Compare kernel variants
- Measure cache effectiveness

#### **Level 3: Expert Introspection** 
- Examine generated kernel source code
- Understand memory access patterns
- Debug numerical accuracy issues

#### **Level 4: Production Monitoring** 
- Real-time performance tracking
- Automated regression detection
- Deployment health monitoring

Let's explore these debugging levels with practical demonstrations:

## The Critical Jupyter Debugging Problem

**Before we explore debugging techniques, we must address a fundamental issue**: **PyTorch debugging logs don't appear in Jupyter notebooks!** This affects every PyTorch developer using notebooks and significantly impacts the debugging experience.

### 🔍 **Why PyTorch Logs Disappear in Jupyter**

```python
# This works perfectly in terminal:
os.environ['TORCH_LOGS'] = 'dynamo'
compiled_model = torch.compile(model)
result = compiled_model(input)  # Shows extensive logs in terminal

# This same code in Jupyter:  
# ❌ No logs visible - even though compilation happens!
```

**Root Cause Analysis:**

1. **PyTorch's Internal Logging**: Written in C++ and goes directly to system `stderr`
2. **Jupyter's Output Capture**: Only captures Python `print()` statements and exceptions
3. **Output Mismatch**: System `stderr` bypasses Jupyter's output capture mechanism
4. **Environment Variables Work**: They configure PyTorch correctly, but output is lost

### **Complete Solutions for Jupyter Debugging**

We'll explore **three proven approaches** that work reliably in Jupyter notebooks:

| Method | Best For | Jupyter Friendly | Detail Level |
|--------|----------|------------------|--------------|
| **1. Subprocess Capture** | Seeing actual PyTorch logs | ✅ Yes | 🔥 Maximum |
| **2. `torch._dynamo.explain()`** | Graph analysis | ✅ Yes | 📊 High |
| **3. Artifact Inspection** | Generated kernels | ✅ Yes | 🔬 Deep |

### **What You'll Learn**

This section will teach you to become a **Jupyter debugging expert** by mastering:

- **Problem-Aware Debugging**: Understanding why standard approaches fail
- **Jupyter-Native Solutions**: Techniques that work reliably in notebooks
- **Hybrid Approaches**: Combining external capture with notebook analysis
- **Production-Ready Methods**: Debugging techniques that scale to real projects

##  Debugging Solutions Overview

### **Method 1: Subprocess Capture**  *For Complete Logging*

**When to use**: When you need to see the actual PyTorch debug logs that would appear in terminal.

```python
# Capture PyTorch logs that Jupyter normally misses
result = subprocess.run(['python', 'debug_script.py'], 
                       env={'TORCH_LOGS': 'dynamo'}, 
                       capture_output=True, text=True)
print(result.stderr)  # Shows actual PyTorch logs!
```

**Pros**: 
- ✅ Shows real PyTorch compilation logs
- ✅ Complete environment variable support
- ✅ Identical to terminal debugging experience

**Cons**: 
- ⚠️ Requires external script creation
- ⚠️ More complex setup

---

### **Method 2: Dynamo Analysis** *Best for Daily Debugging*

**When to use**: For analyzing what gets compiled vs. what causes graph breaks.

```python
# This ALWAYS works in Jupyter
explanation = torch._dynamo.explain(model)(input)
print(f"Graphs: {explanation.graph_count}")
print(f"Breaks: {explanation.graph_break_count}")
```

**Pros**:
- ✅ Native Jupyter support
- ✅ Structured output
- ✅ Perfect for graph analysis
- ✅ Fast and reliable

**Cons**:
- ⚠️ Limited to graph-level insights
- ⚠️ No kernel generation details

---

### **Method 3: Artifact Inspection** *Best for Deep Understanding*

**When to use**: To examine generated Triton kernels and understand optimizations.

```python
# Explore generated kernels
kernel_files = glob.glob('/tmp/torchinductor_*/**/*.py')
with open(kernel_files[0]) as f:
    print(f.read())  # See actual generated Triton code!
```

**Pros**:
- ✅ Deep understanding of optimizations
- ✅ Educational value
- ✅ Real kernel source code
- ✅ Shows actual compilation results

**Cons**:
- ⚠️ Requires file system navigation
- ⚠️ Platform-dependent paths

## Demonstrating the Problem & Solutions

Let's start with a hands-on demonstration that shows **exactly why** standard debugging approaches fail in Jupyter and **how our solutions work**.

In [4]:
import os
import time
import subprocess
import tempfile

def demonstrate_jupyter_logging_problem():
    """
    Demonstrate the fundamental issue: PyTorch logs work in terminal but not Jupyter
    """
    print("🚨 DEMONSTRATING THE JUPYTER LOGGING PROBLEM")
    print("=" * 55)
    
    # Create a simple model that should generate logs
    def simple_fusion_model(x):
        """Model designed to trigger compilation and logging"""
        return torch.tanh(torch.relu(x) * 2.0 + 1.0)
    
    test_input = torch.randn(100, device=device)
    
    print("🎯 Test Case: Simple fusion model (ReLU → Multiply → Add → Tanh)")
    print(f"   Input shape: {test_input.shape}")
    print(f"   Device: {device}")
    print()
    
    # Step 1: Try the "standard" approach that fails in Jupyter
    print("❌ FAILED APPROACH: Environment Variables in Jupyter")
    print("-" * 50)
    
    # Set environment variables that should show logs
    os.environ['TORCH_LOGS'] = 'dynamo'
    os.environ['TORCH_COMPILE_DEBUG'] = '1'
    
    print("Environment variables set:")
    print(f"   TORCH_LOGS = '{os.environ.get('TORCH_LOGS')}'")
    print(f"   TORCH_COMPILE_DEBUG = '{os.environ.get('TORCH_COMPILE_DEBUG')}'")
    print()
    
    print("Compiling model with debug environment...")
    torch._dynamo.reset()  # Clear cache
    
    start_time = time.perf_counter()
    compiled_model = torch.compile(simple_fusion_model)
    result = compiled_model(test_input)
    compilation_time = time.perf_counter() - start_time
    
    print(f"✅ Compilation completed in {compilation_time*1000:.1f} ms")
    print(f"📊 Result shape: {result.shape}")
    print("🔍 Expected: Extensive PyTorch debug logs")
    print("💥 Reality: No debug logs visible in Jupyter!")
    print()
    
    # Clean up environment variables
    os.environ.pop('TORCH_LOGS', None)
    os.environ.pop('TORCH_COMPILE_DEBUG', None)
    
    print("🎓 Key Insight:")
    print("   • Environment variables ARE working (compilation happened)")
    print("   • PyTorch IS generating logs (just not visible)")
    print("   • Jupyter captures Python prints, not system stderr")
    print("   • We need alternative approaches for notebook debugging")
    
    return compilation_time, result.shape

# Execute the demonstration
problem_demo_time, result_shape = demonstrate_jupyter_logging_problem()

🚨 DEMONSTRATING THE JUPYTER LOGGING PROBLEM


🎯 Test Case: Simple fusion model (ReLU → Multiply → Add → Tanh)
   Input shape: torch.Size([100])
   Device: cuda

❌ FAILED APPROACH: Environment Variables in Jupyter
--------------------------------------------------
Environment variables set:
   TORCH_LOGS = 'dynamo'
   TORCH_COMPILE_DEBUG = '1'

Compiling model with debug environment...
✅ Compilation completed in 6430.9 ms
📊 Result shape: torch.Size([100])
🔍 Expected: Extensive PyTorch debug logs
💥 Reality: No debug logs visible in Jupyter!

🎓 Key Insight:
   • Environment variables ARE working (compilation happened)
   • PyTorch IS generating logs (just not visible)
   • Jupyter captures Python prints, not system stderr
   • We need alternative approaches for notebook debugging
✅ Compilation completed in 6430.9 ms
📊 Result shape: torch.Size([100])
🔍 Expected: Extensive PyTorch debug logs
💥 Reality: No debug logs visible in Jupyter!

🎓 Key Insight:
   • Environment variables ARE working (compilation happened)
   • PyTorch IS generat

### ✅ Working Solutions for Jupyter Debugging

Now that we've seen the problem, let's explore the **two proven solutions** that actually work in Jupyter notebooks. Each solution targets different debugging needs and provides reliable insights into PyTorch's compilation process.

## Solution 1: Subprocess Capture Method

**Objective**: Capture the actual PyTorch debug logs that would appear in terminal.

**When to use**: 
- Learning what PyTorch compilation actually does
- Debugging complex compilation issues  
- Seeing environment variable effects
- Educational exploration of internals

**How it works**: Run PyTorch code in an external Python process and capture all output (stdout + stderr) back into the Jupyter notebook.

In [5]:
import tempfile
import subprocess
import sys

def demonstrate_jupyter_vs_terminal_logging():
    """
    Demonstrate the logging problem in Jupyter and show the solution
    """
    print("🔧 The Jupyter vs Terminal Logging Problem")
    print("=" * 50)
    
    # Create a simple test script to run externally
    test_script_content = '''
import torch
import os

def simple_model(x):
    return torch.relu(x * 2.0) + 1.0

def main():
    print("🎯 PyTorch Logging Test (External Process)")
    print("Environment variables active:")
    
    # Show environment variables that were set
    for key in ['TORCH_LOGS', 'TORCH_COMPILE_DEBUG', 'TRITON_PRINT_AUTOTUNING']:
        value = os.environ.get(key, 'Not Set')
        print(f"  {key}: {value}")
    
    print("\\nStarting compilation...")
    
    # Clear cache and compile
    torch._dynamo.reset()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_input = torch.randn(100, device=device)
    
    compiled_model = torch.compile(simple_model)
    result = compiled_model(test_input)
    
    print(f"Compilation completed. Result shape: {result.shape}")
    print("Any logs above this line came from PyTorch!")

if __name__ == "__main__":
    main()
'''
    
    # Create temporary script
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
        f.write(test_script_content)
        temp_script = f.name
    
    try:
        # Test scenarios with different logging levels
        scenarios = [
            {
                "name": "Minimal (No Debug)",
                "env_vars": {},
                "description": "Standard execution without debug output"
            },
            {
                "name": "Basic Dynamo Logging", 
                "env_vars": {"TORCH_LOGS": "+dynamo"},
                "description": "Shows graph capture and compilation decisions"
            },
            {
                "name": "Comprehensive Debug",
                "env_vars": {
                    "TORCH_LOGS": "+dynamo,+inductor",
                    "TORCH_COMPILE_DEBUG": "1"
                },
                "description": "Full debugging with file generation"
            }
        ]
        
        for i, scenario in enumerate(scenarios, 1):
            print(f"\\n{'='*20} Scenario {i}: {scenario['name']} {'='*20}")
            print(f"📝 {scenario['description']}")
            
            # Prepare environment
            env = os.environ.copy()
            env_vars = scenario['env_vars']
            
            if env_vars:
                print("Environment variables set:")
                for key, value in env_vars.items():
                    env[key] = value
                    print(f"  {key}={value}")
            else:
                print("No environment variables set")
            
            print("\\nRunning external Python process...")
            print("-" * 40)
            
            try:
                # Run script with timeout
                result = subprocess.run(
                    [sys.executable, temp_script],
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=20
                )
                
                # Show all output
                if result.stdout.strip():
                    print("📤 STDOUT:")
                    for line in result.stdout.strip().split('\\n'):
                        print(f"   {line}")
                
                if result.stderr.strip():
                    print("\\n📥 STDERR (PyTorch Debug Logs):")
                    stderr_lines = [line for line in result.stderr.strip().split('\\n') if line.strip()]
                    
                    if len(stderr_lines) > 10:
                        # Show first few and last few lines if output is long
                        print(f"   📊 {len(stderr_lines)} debug lines captured!")
                        print("   First 5 lines:")
                        for line in stderr_lines[:5]:
                            print(f"     {line}")
                        print(f"   ... ({len(stderr_lines) - 10} lines omitted) ...")
                        print("   Last 5 lines:")
                        for line in stderr_lines[-5:]:
                            print(f"     {line}")
                    else:
                        # Show all lines if output is short
                        for line in stderr_lines:
                            print(f"   {line}")
                
                # Summary
                total_debug_lines = len([line for line in result.stderr.split('\\n') if line.strip()])
                
                print(f"\\n📊 Results:")
                print(f"   Return code: {result.returncode}")
                print(f"   Debug lines captured: {total_debug_lines}")
                
                if total_debug_lines > 0:
                    print(f"   🎉 SUCCESS: Captured PyTorch debug output!")
                else:
                    print(f"   ℹ️  No debug output (expected for minimal scenario)")
                    
            except subprocess.TimeoutExpired:
                print("   ⏰ Process timed out")
            except Exception as e:
                print(f"   ❌ Error: {e}")
    
    finally:
        # Clean up temporary file
        try:
            os.unlink(temp_script)
        except:
            pass
    
    print(f"\\n💡 Key Insight: Subprocess Capture Solution")
    print("✅ This method works in Jupyter because:")
    print("   • Runs PyTorch in external process")
    print("   • Captures ALL output streams")
    print("   • Shows debug info that Jupyter normally can't see")
    print("   • Provides complete visibility into compilation process")
    
    return True

# Demonstrate the subprocess capture solution
debug_success = demonstrate_jupyter_vs_terminal_logging()

🔧 The Jupyter vs Terminal Logging Problem
\n==================== Scenario 1: Minimal (No Debug) ====================
📝 Standard execution without debug output
No environment variables set
\nRunning external Python process...
----------------------------------------
📤 STDOUT:
   🎯 PyTorch Logging Test (External Process)
Environment variables active:
  TORCH_LOGS: Not Set
  TORCH_COMPILE_DEBUG: Not Set
  TRITON_PRINT_AUTOTUNING: 1

Starting compilation...
Compilation completed. Result shape: torch.Size([100])
Any logs above this line came from PyTorch!
\n📊 Results:
   Return code: 0
   Debug lines captured: 0
   ℹ️  No debug output (expected for minimal scenario)
\n==================== Scenario 2: Basic Dynamo Logging ====================
📝 Shows graph capture and compilation decisions
Environment variables set:
  TORCH_LOGS=+dynamo
\nRunning external Python process...
----------------------------------------
📤 STDOUT:
   🎯 PyTorch Logging Test (External Process)
Environment variables ac


#### **What the Output Shows:**

1. **External Process Capture**: Successfully ran PyTorch code in subprocess and captured ALL output
2. **Environment Variables Work**: `TORCH_LOGS` settings produced different amounts of debug output  
3. **Visible Differences**: Each scenario showed progressively more compilation information
4. **Complete Logging**: Captured both stdout (our prints) and stderr (PyTorch's internal logs)

## Solution 2: Dynamo Analysis Method

**Objective**: Analyze compilation quality and graph breaks using Jupyter-native PyTorch APIs.

**When to use**:
- Understanding what gets compiled vs. what falls back to eager execution
- Identifying graph break causes
- Quick compilation analysis without external processes
- Daily debugging workflows

**Key Advantage**: This method is **100% Jupyter-native** and always works reliably.

### Implementation: torch._dynamo.explain()

The `torch._dynamo.explain()` function provides structured analysis of the compilation process without requiring external logging capture.

In [6]:
def demonstrate_dynamo_analysis():
    """
    Solution 2: Use torch._dynamo.explain() for Jupyter-native debugging
    """
    print("📊 SOLUTION 2: DYNAMO ANALYSIS METHOD")
    print("=" * 45)
    print("✅ This method ALWAYS works in Jupyter!")
    print()
    
    # Create models with different compilation characteristics
    test_models = [
        {
            "name": "Clean Model",
            "function": lambda x: torch.tanh(torch.relu(x) * 2.0 + 1.0),
            "description": "Simple operations that should compile cleanly"
        },
        {
            "name": "Graph Break Model", 
            "function": lambda x: torch.tanh(x) if x.sum() > 0 else torch.relu(x),
            "description": "Contains conditional that causes graph breaks"
        },
        {
            "name": "Complex Model",
            "function": lambda x: torch.mm(torch.relu(x), x.T).sum(dim=1, keepdim=True),
            "description": "Multiple operations with different optimization potential"
        }
    ]
    
    test_input = torch.randn(50, 50, device=device)
    
    for i, model_info in enumerate(test_models, 1):
        print(f"🧪 Model {i}: {model_info['name']}")
        print(f"   Description: {model_info['description']}")
        print("-" * 40)
        
        try:
            # Use dynamo.explain() to analyze compilation
            explanation = torch._dynamo.explain(model_info['function'])(test_input)
            
            print(f"📈 Analysis Results:")
            print(f"   Graph Count: {explanation.graph_count}")
            print(f"   Graph Break Count: {explanation.graph_break_count}")  
            print(f"   Op Count: {explanation.op_count}")
            
            # Interpret results
            if explanation.graph_break_count == 0:
                print(f"   ✅ Excellent: Clean compilation, no graph breaks")
                quality = "Optimal"
            elif explanation.graph_break_count == 1:
                print(f"   ⚠️  Good: Minor graph break, mostly optimized")
                quality = "Good"
            else:
                print(f"   ❌ Poor: Multiple graph breaks, limited optimization")
                quality = "Needs Work"
            
            print(f"   🎯 Compilation Quality: {quality}")
            
            # Show graph break details if available
            if hasattr(explanation, 'graph_breaks') and explanation.graph_breaks:
                print(f"   🔍 Graph Break Reasons:")
                for j, break_reason in enumerate(explanation.graph_breaks[:2], 1):
                    # Truncate long break reasons
                    reason_str = str(break_reason)[:80] + "..." if len(str(break_reason)) > 80 else str(break_reason)
                    print(f"      {j}. {reason_str}")
                    
        except Exception as e:
            print(f"   ❌ Analysis failed: {str(e)[:60]}...")
            quality = "Failed"
        
        print()
    
    print("🎓 Key Benefits of Dynamo Analysis:")
    print("   ✅ Always works in Jupyter (no external processes)")
    print("   ✅ Structured, programmatic output") 
    print("   ✅ Perfect for automated analysis")
    print("   ✅ Identifies specific issues (graph breaks)")
    print("   ✅ Fast execution (no compilation needed)")
    
    return True

# Execute dynamo analysis demonstration  
dynamo_success = demonstrate_dynamo_analysis()

📊 SOLUTION 2: DYNAMO ANALYSIS METHOD
✅ This method ALWAYS works in Jupyter!

🧪 Model 1: Clean Model
   Description: Simple operations that should compile cleanly
----------------------------------------
📈 Analysis Results:
   Graph Count: 1
   Graph Break Count: 0
   Op Count: 4
   ✅ Excellent: Clean compilation, no graph breaks
   🎯 Compilation Quality: Optimal

🧪 Model 2: Graph Break Model
   Description: Contains conditional that causes graph breaks
----------------------------------------
📈 Analysis Results:
   Graph Count: 2
   Graph Break Count: 1
   Op Count: 2
   ⚠️  Good: Minor graph break, mostly optimized
   🎯 Compilation Quality: Good

🧪 Model 3: Complex Model
   Description: Multiple operations with different optimization potential
----------------------------------------
📈 Analysis Results:
   Graph Count: 1
   Graph Break Count: 0
   Op Count: 4
   ✅ Excellent: Clean compilation, no graph breaks
   🎯 Compilation Quality: Optimal

🧪 Model 2: Graph Break Model
   Descripti

## Solution 3: Artifact Inspection Method

**Objective**: Examine generated Triton kernels and compilation artifacts to understand deep optimizations.

**When to use**:
- Learning how PyTorch optimizes specific operations
- Understanding kernel fusion strategies  
- Educational exploration of generated code
- Deep performance analysis

**Key Value**: See the **actual optimized code** that PyTorch generates, providing insights into compilation strategies.

### **Production TorchInductor Debugger Architecture**

This method explores the file system locations where PyTorch stores generated kernels and compilation artifacts, providing direct access to optimized code. To this end, we'll implement a **production-ready solution** that completely eliminates directory conflicts. This solution addresses the core problems:

### **Design Goals**
- **Isolated directories** for each debugging session
- **Automatic artifact capture** from TorchInductor's default locations  
- **Organized file structure** with kernels and binaries separated
- **Built-in analysis tools** for understanding generated code
- **Clean session management** with context managers

### **Architecture Overview**

The `ProductionTorchInductorDebugger` class provides:

1. **Session Management**: Each debug session gets a unique directory
2. **Artifact Capture**: Automatically finds and copies TorchInductor artifacts  
3. **File Organization**: Separates Python kernels from compiled binaries
4. **Analysis Tools**: Built-in kernel inspection and optimization detection
5. **Cleanup Control**: Choose whether to preserve or remove artifacts

Let's implement this step by step, starting with the core class structure.

#### **Step 1: Core Class Structure & Session Management**

The foundation of our solution is a context manager that creates isolated directories and handles cleanup automatically.

#### **Step 2: Model Compilation & Artifact Capture**

This is the core functionality that compiles models and captures their generated artifacts. The process:

1. **Clear previous artifacts** to ensure we only capture new ones
2. **Compile the model** with optimized settings to force artifact generation  
3. **Execute the model** to trigger actual code generation
4. **Capture artifacts** from TorchInductor's default location into our isolated directory

#### **Step 3: Artifact Organization & File Management**

This section handles the intelligent organization of captured artifacts. The system:

1. **Scans multiple file types**: Python kernels (`.py`), CUDA binaries (`.cubin`), PTX assembly (`.ptx`)
2. **Filters substantial files**: Ignores tiny or empty files that aren't useful for analysis
3. **Organizes by type**: Separates kernels and binaries into different directories
4. **Creates descriptive names**: Renames files with sequential numbering for easy identification

#### **Step 4: Intelligent Artifact Analysis**

The analysis engine examines captured artifacts to provide insights into TorchInductor's optimizations. It provides:

1. **Kernel inspection**: Finds and analyzes the largest/most complex generated kernels
2. **Source code preview**: Shows the actual generated Triton code  
3. **Optimization detection**: Identifies patterns like operation fusion, autotuning, memory optimization
4. **Performance insights**: Counts key optimization indicators to understand what PyTorch optimized


In [42]:
class ProductionTorchInductorDebugger:
    """
    Production-ready TorchInductor artifact debugger
    
    Solves the directory conflict problem by:
    1. Creating isolated directories for each debug session
    2. Automatically capturing artifacts from TorchInductor
    3. Providing clean analysis tools
    4. Managing cleanup appropriately
    """
    
    def __init__(self, session_name: str = None, auto_cleanup: bool = False):
        self.session_name = session_name or f"debug_{int(time.time())}"
        self.auto_cleanup = auto_cleanup
        self.custom_dir = None
        self.artifacts_captured = []
        
    def __enter__(self):
        # Create clean custom directory
        self.custom_dir = tempfile.mkdtemp(prefix=f"torch_debug_{self.session_name}_")
        print(f"🔧 TorchInductor Debug Session: '{self.session_name}'")
        print(f"📁 Artifact directory: {self.custom_dir}")
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.auto_cleanup and self.custom_dir:
            shutil.rmtree(self.custom_dir, ignore_errors=True)
            print(f"🧹 Cleaned up debug directory")
        else:
            print(f"💾 Debug artifacts preserved at: {self.custom_dir}")

    #### **Step 2: Model Compilation & Artifact Capture
    def compile_and_capture_artifacts(self, model_fn, test_input, **compile_kwargs):
        """
        Compile a model and capture its artifacts in our custom directory
        
        Args:
            model_fn: Function to compile
            test_input: Input tensor for testing
            **compile_kwargs: Additional arguments for torch.compile()
        """
        # Default compilation settings that encourage artifact generation
        default_kwargs = {
            'backend': 'inductor',
            'mode': 'max-autotune'
        }
        default_kwargs.update(compile_kwargs)
        
        # Get default TorchInductor location
        user_name = os.getenv('USER', 'user')
        default_location = f"/tmp/torchinductor_{user_name}"
        
        # Clear previous artifacts to ensure we capture new ones
        if os.path.exists(default_location):
            print(f"🧹 Clearing previous artifacts...")
            subprocess.run(f"rm -rf {default_location}/*", shell=True, capture_output=True)
        
        # Reset dynamo and compile
        torch._dynamo.reset()
        torch._inductor.codecache.FxGraphCache.clear()
        print(f"🔄 Compiling model with {default_kwargs}...")
        
        compiled_model = torch.compile(model_fn, **default_kwargs)
        result = compiled_model(test_input)
        
        print(f"✅ Model compiled and executed (output shape: {result.shape})")
        
        # Capture artifacts
        time.sleep(0.5)  # Allow file system to sync
        self._capture_artifacts_from_default_location(default_location)
        
        return result

    # Step 3: Artifact Organization & File Management
    def _capture_artifacts_from_default_location(self, default_location):
        """Copy artifacts from default location to our custom directory"""
        if not os.path.exists(default_location):
            print(f"⚠️  Default location not found: {default_location}")
            return
        
        # Find all artifact files
        artifact_patterns = [
            "**/*.py",     # Python kernels
            "**/*.cubin",  # CUDA binaries  
            "**/*.ptx",    # PTX assembly
        ]
        
        all_artifacts = []
        for pattern in artifact_patterns:
            matches = glob.glob(f"{default_location}/{pattern}", recursive=True)
            all_artifacts.extend(matches)
        
        # Filter for substantial files
        substantial_artifacts = []
        for artifact in all_artifacts:
            try:
                size = os.path.getsize(artifact)
                if size > 100:  # Skip tiny files
                    substantial_artifacts.append((artifact, size))
            except:
                pass
        
        if not substantial_artifacts:
            print(f"⚠️  No substantial artifacts found in {default_location}")
            return
        
        # Copy to our custom directory with organized structure
        print(f"📁 Capturing {len(substantial_artifacts)} artifacts...")
        
        kernels_dir = os.path.join(self.custom_dir, "kernels")
        binaries_dir = os.path.join(self.custom_dir, "binaries")
        os.makedirs(kernels_dir, exist_ok=True)
        os.makedirs(binaries_dir, exist_ok=True)
        
        for src_file, size in substantial_artifacts:
            # Organize by file type
            if src_file.endswith('.py'):
                dst_dir = kernels_dir
                prefix = "kernel"
            else:
                dst_dir = binaries_dir  
                prefix = "binary"
            
            # Create descriptive filename
            original_name = os.path.basename(src_file)
            dst_file = os.path.join(dst_dir, f"{prefix}_{len(self.artifacts_captured)+1}_{original_name}")
            
            try:
                shutil.copy2(src_file, dst_file)
                self.artifacts_captured.append((dst_file, size))
                print(f"   ✅ {os.path.splitext(original_name)[1]}: {original_name} ({size} bytes)")
            except Exception as e:
                print(f"   ⚠️  Failed to copy {original_name}: {e}")

    # Step 4: Artifact Analysis
    def analyze_artifacts(self):
        """Analyze captured artifacts"""
        if not self.artifacts_captured:
            print("❌ No artifacts to analyze")
            return None
            
        print(f"\n🔍 ARTIFACT ANALYSIS")
        print("=" * 25)
        print(f"Total artifacts captured: {len(self.artifacts_captured)}")
        
        # Find largest Python kernel
        py_artifacts = [(f, s) for f, s in self.artifacts_captured if f.endswith('.py')]
        
        if not py_artifacts:
            print("⚠️  No Python kernels found")
            return None
        
        largest_kernel, largest_size = max(py_artifacts, key=lambda x: x[1])
        
        try:
            with open(largest_kernel, 'r') as f:
                content = f.read()
            
            lines = content.split('\n')
            print(f"\n📄 Largest Kernel Analysis:")
            print(f"   File: {os.path.basename(largest_kernel)}")
            print(f"   Size: {largest_size} bytes")
            print(f"   Lines: {len(lines)}")
            
            # Show preview
            print(f"\n📝 Source Preview (first 8 lines):")
            for i, line in enumerate(lines[:8], 1):
                display_line = line[:70] + "..." if len(line) > 70 else line
                print(f"   {i:2d}: {display_line}")
            
            # Pattern analysis
            patterns = {
                'Triton kernels (@triton.jit)': content.count('@triton.jit'),
                'Memory loads (tl.load)': content.count('tl.load'),
                'Memory stores (tl.store)': content.count('tl.store'),
                'Operation fusion (fused)': content.count('fused'),
                'Autotuning (autotuned)': content.count('autotuned'),
                'Grid computations (tl.program_id)': content.count('tl.program_id'),
            }
            
            detected_optimizations = {k: v for k, v in patterns.items() if v > 0}
            
            if detected_optimizations:
                print(f"\n⚡ Detected Optimizations:")
                for optimization, count in detected_optimizations.items():
                    print(f"   ✅ {optimization}: {count}")
            else:
                print(f"\n   ℹ️  No obvious optimization patterns detected")
            
            return content
            
        except Exception as e:
            print(f"❌ Could not analyze kernel: {e}")
            return None
    
    def get_artifact_summary(self):
        """Get summary of captured artifacts"""
        if not self.artifacts_captured:
            return "No artifacts captured"
        
        py_files = sum(1 for f, _ in self.artifacts_captured if f.endswith('.py'))
        other_files = len(self.artifacts_captured) - py_files
        total_size = sum(s for _, s in self.artifacts_captured)
        
        return f"Captured: {py_files} Python kernels, {other_files} other files ({total_size:,} bytes total)"

### **Production Demonstration**

Now let's demonstrate the complete solution in action. This demonstration will:

1. **Create a realistic model** with multiple optimization opportunities
2. **Use the debugger** to compile and capture artifacts in an isolated directory
3. **Analyze the results** to see what optimizations TorchInductor applied
4. **Show the clean directory structure** with organized artifacts

This proves the solution works end-to-end and eliminates directory conflicts.

In [39]:
def demo_production_debugging():
    """Demonstrate the production-ready debugging solution"""
    print("🚀 PRODUCTION TORCHINDEUCTOR DEBUGGING")
    print("=" * 45)
    
    with ProductionTorchInductorDebugger("production_demo", auto_cleanup=False) as debugger:
        
        def optimizable_model(x):
            """Model with multiple optimization opportunities"""
            # Operations that should trigger kernel generation
            y = torch.relu(x)              # Activation
            z = y * 3.0 + 0.5             # Fused multiply-add
            w = torch.tanh(z)              # Another activation
            return w.sum(dim=0, keepdim=True).expand_as(x)  # Reduction + broadcast
        
        # Test with substantial input
        test_input = torch.randn(1500, device=device)
        
        # Compile and capture artifacts
        result = debugger.compile_and_capture_artifacts(
            optimizable_model, 
            test_input,
            mode="max-autotune"  # Force aggressive optimization
        )
        
        print(f"\n📊 {debugger.get_artifact_summary()}")
        
        # Analyze artifacts
        kernel_content = debugger.analyze_artifacts()
        
        if kernel_content:
            print(f"\n✅ SUCCESS: TorchInductor artifacts captured and analyzed!")
            print(f"📂 Artifacts location: {debugger.custom_dir}")
        else:
            print(f"\n  Limited success - check directory manually")
    
    return True

print("🏭 ProductionTorchInductorDebugger loaded!")
print("   Clean, isolated, production-ready artifact debugging")

# Execute the production debugging demonstration
success = demo_production_debugging()

if success:
    print(f"\n🎉 COMPLETE SUCCESS!")
    print(f"✅ Clean directory isolation achieved")
    print(f"✅ Artifacts captured and organized") 
    print(f"✅ No conflicts with other processes")
    print(f"✅ Production-ready debugging solution verified!")

🏭 ProductionTorchInductorDebugger loaded!
   Clean, isolated, production-ready artifact debugging
🚀 PRODUCTION TORCHINDEUCTOR DEBUGGING
🔧 TorchInductor Debug Session: 'production_demo'
📁 Artifact directory: /tmp/torch_debug_production_demo_tqibp5sv
🧹 Clearing previous artifacts...
🔄 Compiling model with {'backend': 'inductor', 'mode': 'max-autotune'}...
✅ Model compiled and executed (output shape: torch.Size([1500]))
📁 Capturing 18 artifacts...
   ✅ .py: cxcnucfdc3orragmmwk5y2k3bkdrwpt23i3z4bi44pbxrmqhv3d6.py (2973 bytes)
   ✅ .py: chblowbn2shg4mdx6d66zzg7ccs4u5b2txxlvejbstoy67v2fddf.py (6551 bytes)
   ✅ .cubin: triton_red_fused_add_mul_relu_sum_tanh_0.cubin (9328 bytes)
   ✅ .cubin: triton_red_fused_add_mul_relu_sum_tanh_0.cubin (23984 bytes)
   ✅ .cubin: triton_red_fused_add_mul_relu_sum_tanh_0.cubin (16176 bytes)
   ✅ .cubin: triton_red_fused_add_mul_relu_sum_tanh_0.cubin (12464 bytes)
   ✅ .cubin: triton_red_fused_add_mul_relu_sum_tanh_0.cubin (16304 bytes)
   ✅ .cubin: triton_red_

#### **Clean TorchInductor Artifact Debugging**

##### **Problem Solved** 

The original artifact inspection used shared TorchInductor directories like `/tmp/torchinductor_user` which caused:
- **Conflicts** with other PyTorch processes
- **Mixed artifacts** from different debugging sessions  
- **Confusion** about which files belong to which experiment

##### **Production Solution** 

```python
# Clean, isolated debugging session
with ProductionTorchInductorDebugger("my_experiment", auto_cleanup=False) as debugger:
    
    def my_model(x):
        return torch.relu(x * 2.0 + 1.0)
    
    # Compile and automatically capture artifacts in clean directory
    result = debugger.compile_and_capture_artifacts(my_model, test_input)
    
    # Analyze captured artifacts
    debugger.analyze_artifacts()
    
    # Get summary: "Captured: 2 Python kernels, 1 other files (8,715 bytes total)"
    print(debugger.get_artifact_summary())

# Artifacts preserved in organized directory structure:
# /tmp/torch_debug_my_experiment_xyz/
#   ├── kernels/
#   │   ├── kernel_1_optimized_relu.py
#   │   └── kernel_2_fused_ops.py  
#   └── binaries/
#       └── binary_1_compiled.cubin
```

##### **Key Benefits** 

| Feature | Benefit |
|---------|---------|
| **Isolated Directories** | No conflicts with other processes |
| **Organized Structure** | kernels/ and binaries/ subdirectories |
| **Session Naming** | Easy to identify different experiments |
| **Flexible Cleanup** | Choose to preserve or auto-remove |
| **Built-in Analysis** | Automatic kernel inspection and pattern detection |
| **Fresh Compilation** | Clears cache to ensure new artifacts |

##### **Usage Patterns** 

**Quick Experiment:**
```python
with ProductionTorchInductorDebugger("quick_test", auto_cleanup=True) as debug:
    result = debug.compile_and_capture_artifacts(model, input)
    # Auto-cleanup on exit
```

**Detailed Analysis:**
```python  
with ProductionTorchInductorDebugger("performance_study", auto_cleanup=False) as debug:
    result = debug.compile_and_capture_artifacts(model, input, mode="max-autotune")
    kernel_code = debug.analyze_artifacts()  # See actual generated code
    # Artifacts preserved for later inspection
```

This approach provides **production-ready debugging** with complete isolation and organization!

## Jupyter Debugging Toolkit Summary

We've explored **three focused solutions** for debugging `torch.compile()` in Jupyter notebooks. Each approach addresses the fundamental logging issue while providing unique insights.

**Solution Comparison Matrix**

| Solution | Jupyter Native | Setup Complexity | Information Depth | Best Use Case |
|----------|----------------|------------------|-------------------|---------------|
| **1. Subprocess Capture** | ⚠️ Hybrid | 🔴 High | 🔥 Maximum | Complete PyTorch logs |
| **2. Dynamo Analysis** | ✅ Yes | 🟢 Low | 📊 High | Daily debugging workflow |
| **3. Artifact Inspection** | ✅ Yes | 🟡 Medium | 🔬 Deep | Understanding optimizations |

**Recommended Debugging Workflow**

For most Jupyter debugging scenarios, use this **focused approach**:

#### **Primary Tools** (Use these most often)
1. **Dynamo Analysis** - Check for graph breaks and compilation quality
2. **Artifact Inspection** - Examine generated kernels for optimization insights

**Complete Investigation:** (When you need everything)

3. **Subprocess Capture** - See complete PyTorch logs when environment variables are critical

**Key Insights Achieved**

**Problem Understood**: PyTorch logs work but aren't visible in Jupyter  
**Focused Solutions**: Three practical methods that work reliably  
**Preferred Workflow**: Dynamo Analysis + Artifact Inspection for most needs  
**Production Ready**: Methods suitable for real development workflows  


You now have a **streamlined debugging toolkit** focused on the most effective methods:

- **Dynamo Analysis**: Your daily go-to for quick compilation assessment
- **Artifact Inspection**: Your deep-dive tool for understanding optimizations  
- **Subprocess Capture**: Your comprehensive tool when you need complete logs

This focused foundation enables efficient debugging and prepares you for advanced optimization techniques.

# Systematic Kernel Exploration and Analysis

Beyond environment variables, `torch.compile()` generates tangible artifacts that you can examine directly. Understanding these files provides deeper insights into PyTorch's optimization strategies and helps debug performance issues.

### What We'll Explore

1. **Kernel Storage Locations**: Where PyTorch stores generated artifacts
2. **File Type Analysis**: Understanding different artifact categories  
3. **Python/Triton Kernel Analysis**: Examining the actual generated code
4. **Performance Artifacts**: Binary kernels and metadata analysis

### Expected Locations

- **Primary Cache**: `/tmp/torchinductor_<username>/` - Main kernel storage
- **Debug Traces**: `./torch_compile_debug/` - Created when `TORCH_COMPILE_DEBUG=1`
- **File Types**: `.py` (kernel source), `.so` (compiled libraries), `.json` (metadata)

Let's systematically explore these artifacts to understand what PyTorch generates during compilation.

In [44]:
# Additional imports for kernel exploration
import os
import glob
import json
from pathlib import Path

# Setup for kernel exploration
print("🔧 Setting up kernel exploration...")
print("   Required imports: os, glob, json, pathlib")
print("   Ready to analyze compilation artifacts")

🔧 Setting up kernel exploration...
   Required imports: os, glob, json, pathlib
   Ready to analyze compilation artifacts


In [45]:
import tempfile
import shutil
import subprocess
import warnings
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional, Any
import statistics

@dataclass
class KernelArtifact:
    """Data class for storing kernel artifact information"""
    path: str
    file_type: str
    size_bytes: int
    creation_time: float
    content_summary: str

class ProductionTorchInductorDebugger:
    """
    Production-ready debugger for systematic kernel exploration and analysis.
    Integrates with artifact inspection for comprehensive debugging workflows.
    """
    
    def __init__(self, 
                 device: str = None,
                 cache_cleanup: bool = True,
                 debug_artifacts: bool = True,
                 verbose: bool = True):
        """
        Initialize the production debugger with optimal settings.
        
        Args:
            device: Target device ('cuda' or 'cpu')
            cache_cleanup: Whether to clean cache between runs
            debug_artifacts: Whether to enable artifact generation
            verbose: Whether to print detailed information
        """
        # Device setup
        self.device = device or ('cuda' if torch.cuda.is_available() else 'cpu')
        self.cache_cleanup = cache_cleanup
        self.debug_artifacts = debug_artifacts
        self.verbose = verbose
        
        # Environment setup
        self._setup_environment()
        
        # Storage for artifacts and analysis
        self.artifacts: Dict[str, List[KernelArtifact]] = {}
        self.compilation_logs: List[str] = []
        self.kernel_analysis: Dict[str, Any] = {}
        
        # Benchmarking parameters
        self.warmup_trials = 3
        self.num_trials = 10
        
        if self.verbose:
            print(f"🚀 ProductionTorchInductorDebugger initialized")
            print(f"   Device: {self.device}")
            print(f"   Debug artifacts: {self.debug_artifacts}")
            print(f"   Cache cleanup: {self.cache_cleanup}")
    
    def _setup_environment(self):
        """Setup optimal environment variables for kernel exploration"""
        env_settings = {
            # Core debugging settings
            'TORCH_COMPILE_DEBUG': '1' if self.debug_artifacts else '0',
            'TORCHINDUCTOR_CACHE_DIR': None,  # Use default location
            
            # Performance and verbosity
            'TORCH_LOGS': '+dynamo,+inductor,+graph_code',
            'TORCHINDUCTOR_VERBOSE': '1',
            
            # Kernel optimization settings
            'TORCHINDUCTOR_MAX_AUTOTUNE': '1',
            'TORCHINDUCTOR_COORDINATE_DESCENT_TUNING': '1',
            
            # Memory and compilation settings
            'TORCHINDUCTOR_FREEZING': '1',
            'TORCHINDUCTOR_FX_GRAPH_CACHE': '1',
            
            # Error handling
            'TORCHINDUCTOR_FALLBACK_RANDOM': '0',
        }
        
        if self.verbose:
            print("\n🔧 Setting up environment for kernel exploration:")
        
        for key, value in env_settings.items():
            if value is not None:
                os.environ[key] = str(value)
                if self.verbose:
                    print(f"   {key} = {value}")
            elif key in os.environ:
                if self.verbose:
                    print(f"   {key} = {os.environ[key]} (existing)")
    
    def explore_compilation_artifacts(self, model, input_tensor, model_name: str = "model"):
        """
        Comprehensive exploration of compilation artifacts with analysis.
        
        Args:
            model: PyTorch model to compile and analyze
            input_tensor: Input tensor for the model
            model_name: Name for identification in artifacts
        
        Returns:
            Dict containing comprehensive artifact analysis
        """
        if self.verbose:
            print(f"\n🔍 SYSTEMATIC KERNEL EXPLORATION: {model_name}")
            print("=" * 60)
        
        # Step 1: Clean environment if requested
        if self.cache_cleanup:
            self._clean_cache()
        
        # Step 2: Locate initial storage locations
        initial_locations = self._locate_kernel_storage()
        
        # Step 3: Compile model and capture artifacts
        compiled_model, compilation_info = self._compile_with_artifact_capture(
            model, input_tensor, model_name
        )
        
        # Step 4: Discover and analyze artifacts
        artifact_analysis = self._discover_and_analyze_artifacts(model_name)
        
        # Step 5: Kernel-specific analysis
        kernel_analysis = self._analyze_kernels(model_name)
        
        # Step 6: Performance correlation analysis
        performance_analysis = self._correlate_artifacts_with_performance(
            compiled_model, input_tensor, model_name
        )
        
        # Compile comprehensive results
        results = {
            'model_name': model_name,
            'device': self.device,
            'initial_locations': initial_locations,
            'compilation_info': compilation_info,
            'artifact_analysis': artifact_analysis,
            'kernel_analysis': kernel_analysis,
            'performance_analysis': performance_analysis,
            'environment_snapshot': self._capture_environment_snapshot()
        }
        
        if self.verbose:
            self._print_exploration_summary(results)
        
        return results
    
    def _locate_kernel_storage(self) -> Dict[str, str]:
        """Locate all kernel storage directories"""
        locations = {}
        
        # Primary cache location
        user_name = os.getenv('USER', 'user')
        primary_cache = f"/tmp/torchinductor_{user_name}"
        
        # Debug traces location
        debug_dir = "./torch_compile_debug"
        
        # Additional possible locations
        temp_dirs = [
            tempfile.gettempdir() + "/torchinductor*",
            os.path.expanduser("~/.cache/torch"),
            "./triton_cache"
        ]
        
        if os.path.exists(primary_cache):
            locations['primary_cache'] = primary_cache
        
        if os.path.exists(debug_dir):
            locations['debug_traces'] = debug_dir
        
        # Search for additional cache directories
        for pattern in temp_dirs:
            found_dirs = glob.glob(pattern)
            for dir_path in found_dirs:
                if os.path.isdir(dir_path):
                    locations[f'additional_{os.path.basename(dir_path)}'] = dir_path
        
        if self.verbose:
            print(f"\n📁 Located storage directories:")
            for name, path in locations.items():
                print(f"   {name}: {path}")
        
        return locations
    
    def _compile_with_artifact_capture(self, model, input_tensor, model_name: str):
        """Compile model while capturing detailed compilation information"""
        compilation_info = {
            'start_time': time.time(),
            'cache_before': self._get_cache_stats(),
        }
        
        if self.verbose:
            print(f"\n⚙️ Compiling {model_name} with artifact capture...")
        
        # Reset Dynamo cache for clean compilation
        torch._dynamo.reset()
        
        # Compile model
        try:
            start_time = time.perf_counter()
            compiled_model = torch.compile(model, backend='inductor', mode='default')
            
            # First inference to trigger full compilation
            with torch.no_grad():
                _ = compiled_model(input_tensor)
            
            if torch.cuda.is_available():
                torch.cuda.synchronize()
            
            compilation_time = time.perf_counter() - start_time
            
            compilation_info.update({
                'success': True,
                'compilation_time_ms': compilation_time * 1000,
                'cache_after': self._get_cache_stats(),
                'error': None
            })
            
            if self.verbose:
                print(f"   ✅ Compilation successful in {compilation_time*1000:.1f}ms")
        
        except Exception as e:
            compilation_info.update({
                'success': False,
                'compilation_time_ms': 0,
                'error': str(e)
            })
            
            if self.verbose:
                print(f"   ❌ Compilation failed: {e}")
            
            return None, compilation_info
        
        return compiled_model, compilation_info
    
    def _discover_and_analyze_artifacts(self, model_name: str) -> Dict[str, Any]:
        """Discover and categorize all compilation artifacts"""
        if self.verbose:
            print(f"\n🔎 Discovering artifacts for {model_name}...")
        
        artifact_analysis = {
            'total_files': 0,
            'file_types': {},
            'storage_locations': {},
            'artifacts_by_type': {},
            'size_analysis': {}
        }
        
        # Get current storage locations
        locations = self._locate_kernel_storage()
        
        all_artifacts = []
        
        for location_name, location_path in locations.items():
            if not os.path.exists(location_path):
                continue
            
            location_artifacts = []
            
            # Recursively find all files
            for root, dirs, files in os.walk(location_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    try:
                        stat_info = os.stat(file_path)
                        file_ext = os.path.splitext(file)[1] or 'no_ext'
                        
                        artifact = KernelArtifact(
                            path=file_path,
                            file_type=file_ext,
                            size_bytes=stat_info.st_size,
                            creation_time=stat_info.st_mtime,
                            content_summary=self._analyze_file_content(file_path, file_ext)
                        )
                        
                        location_artifacts.append(artifact)
                        all_artifacts.append(artifact)
                        
                    except (OSError, PermissionError):
                        continue
            
            artifact_analysis['storage_locations'][location_name] = {
                'path': location_path,
                'file_count': len(location_artifacts),
                'artifacts': location_artifacts
            }
        
        # Categorize by file type
        type_counts = {}
        type_sizes = {}
        
        for artifact in all_artifacts:
            file_type = artifact.file_type
            type_counts[file_type] = type_counts.get(file_type, 0) + 1
            type_sizes[file_type] = type_sizes.get(file_type, 0) + artifact.size_bytes
        
        artifact_analysis.update({
            'total_files': len(all_artifacts),
            'file_types': type_counts,
            'size_analysis': type_sizes,
            'artifacts_by_type': self._group_artifacts_by_type(all_artifacts)
        })
        
        if self.verbose:
            print(f"   📊 Found {len(all_artifacts)} artifacts across {len(locations)} locations")
            for file_type, count in type_counts.items():
                size_mb = type_sizes.get(file_type, 0) / (1024 * 1024)
                print(f"      {file_type}: {count} files ({size_mb:.2f} MB)")
        
        return artifact_analysis
    
    def _analyze_kernels(self, model_name: str) -> Dict[str, Any]:
        """Detailed analysis of generated kernels"""
        if self.verbose:
            print(f"\n🧬 Analyzing kernels for {model_name}...")
        
        kernel_analysis = {
            'python_kernels': [],
            'triton_kernels': [],
            'cpp_kernels': [],
            'binary_kernels': [],
            'statistics': {}
        }
        
        # Find kernel files in discovered artifacts
        if hasattr(self, 'artifacts') and model_name in self.artifacts:
            artifacts = self.artifacts[model_name]
        else:
            # Fallback: search for kernel files
            artifacts = self._find_kernel_files()
        
        python_count = 0
        triton_count = 0
        cpp_count = 0
        binary_count = 0
        
        for artifact in artifacts:
            if artifact.file_type == '.py':
                # Analyze Python kernel
                kernel_info = self._analyze_python_kernel(artifact.path)
                if kernel_info:
                    kernel_analysis['python_kernels'].append(kernel_info)
                    python_count += 1
            
            elif artifact.file_type in ['.ttir', '.ttgir', '.llir']:
                # Analyze Triton kernel
                kernel_info = self._analyze_triton_kernel(artifact.path)
                if kernel_info:
                    kernel_analysis['triton_kernels'].append(kernel_info)
                    triton_count += 1
            
            elif artifact.file_type in ['.cpp', '.cu']:
                # Analyze C++/CUDA kernel
                kernel_info = self._analyze_cpp_kernel(artifact.path)
                if kernel_info:
                    kernel_analysis['cpp_kernels'].append(kernel_info)
                    cpp_count += 1
            
            elif artifact.file_type in ['.so', '.cubin', '.ptx']:
                # Analyze binary kernel
                kernel_info = self._analyze_binary_kernel(artifact.path)
                if kernel_info:
                    kernel_analysis['binary_kernels'].append(kernel_info)
                    binary_count += 1
        
        kernel_analysis['statistics'] = {
            'python_kernels': python_count,
            'triton_kernels': triton_count,
            'cpp_kernels': cpp_count,
            'binary_kernels': binary_count,
            'total_kernels': python_count + triton_count + cpp_count + binary_count
        }
        
        if self.verbose:
            stats = kernel_analysis['statistics']
            print(f"   🔢 Kernel Statistics:")
            print(f"      Python kernels: {stats['python_kernels']}")
            print(f"      Triton kernels: {stats['triton_kernels']}")
            print(f"      C++/CUDA kernels: {stats['cpp_kernels']}")
            print(f"      Binary kernels: {stats['binary_kernels']}")
            print(f"      Total kernels: {stats['total_kernels']}")
        
        return kernel_analysis
    
    def _correlate_artifacts_with_performance(self, compiled_model, input_tensor, model_name: str):
        """Correlate discovered artifacts with actual performance"""
        if self.verbose:
            print(f"\n📈 Performance correlation analysis for {model_name}...")
        
        if compiled_model is None:
            return {'error': 'No compiled model available for performance analysis'}
        
        # Benchmark the compiled model
        performance_times = self._benchmark_compiled_model(compiled_model, input_tensor)
        
        # Get kernel statistics
        kernel_stats = self.kernel_analysis.get(model_name, {}).get('statistics', {})
        
        # Calculate correlations
        total_kernels = kernel_stats.get('total_kernels', 0)
        mean_time_ms = statistics.mean(performance_times) * 1000 if performance_times else 0
        
        correlation_analysis = {
            'mean_execution_time_ms': mean_time_ms,
            'execution_times_ms': [t * 1000 for t in performance_times],
            'total_kernels': total_kernels,
            'kernels_per_ms': total_kernels / mean_time_ms if mean_time_ms > 0 else 0,
            'performance_efficiency': self._calculate_efficiency_metrics(kernel_stats, mean_time_ms)
        }
        
        if self.verbose:
            print(f"   ⏱️ Mean execution time: {mean_time_ms:.3f}ms")
            print(f"   🔧 Total kernels: {total_kernels}")
            print(f"   📊 Kernels per ms: {correlation_analysis['kernels_per_ms']:.2f}")
        
        return correlation_analysis
    
    def _benchmark_compiled_model(self, compiled_model, input_tensor) -> List[float]:
        """Benchmark compiled model performance"""
        compiled_model.eval()
        times = []
        
        with torch.no_grad():
            # Warmup
            for _ in range(self.warmup_trials):
                _ = compiled_model(input_tensor)
            
            if torch.cuda.is_available():
                torch.cuda.synchronize()
            
            # Measurement
            for _ in range(self.num_trials):
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                
                start_time = time.perf_counter()
                _ = compiled_model(input_tensor)
                
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                
                times.append(time.perf_counter() - start_time)
        
        return times
    
    def _clean_cache(self):
        """Clean compilation cache"""
        if self.verbose:
            print("\n🧹 Cleaning compilation cache...")
        
        torch._dynamo.reset()
        
        # Clear additional caches if they exist
        user_name = os.getenv('USER', 'user')
        cache_dir = f"/tmp/torchinductor_{user_name}"
        
        if os.path.exists(cache_dir):
            try:
                shutil.rmtree(cache_dir)
                if self.verbose:
                    print(f"   ✅ Cleared cache directory: {cache_dir}")
            except Exception as e:
                if self.verbose:
                    print(f"   ⚠️ Could not clear cache: {e}")
    
    def _get_cache_stats(self) -> Dict[str, Any]:
        """Get current cache statistics"""
        user_name = os.getenv('USER', 'user')
        cache_dir = f"/tmp/torchinductor_{user_name}"
        
        if not os.path.exists(cache_dir):
            return {'exists': False, 'file_count': 0, 'total_size': 0}
        
        file_count = 0
        total_size = 0
        
        for root, dirs, files in os.walk(cache_dir):
            file_count += len(files)
            for file in files:
                try:
                    file_path = os.path.join(root, file)
                    total_size += os.path.getsize(file_path)
                except OSError:
                    continue
        
        return {
            'exists': True,
            'file_count': file_count,
            'total_size': total_size,
            'path': cache_dir
        }
    
    def _analyze_file_content(self, file_path: str, file_ext: str) -> str:
        """Analyze file content to create summary"""
        try:
            if file_ext in ['.py', '.cpp', '.cu', '.h']:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read(500)  # First 500 chars
                    lines = content.count('\n')
                    return f"Text file, {lines} lines"
            
            elif file_ext in ['.so', '.cubin', '.ptx']:
                size = os.path.getsize(file_path)
                return f"Binary file, {size} bytes"
            
            elif file_ext == '.json':
                with open(file_path, 'r') as f:
                    data = json.load(f)
                    return f"JSON, {len(data)} entries" if isinstance(data, dict) else "JSON data"
            
            else:
                size = os.path.getsize(file_path)
                return f"Unknown type, {size} bytes"
        
        except Exception:
            return "Analysis failed"
    
    def _group_artifacts_by_type(self, artifacts: List[KernelArtifact]) -> Dict[str, List[KernelArtifact]]:
        """Group artifacts by type for easier analysis"""
        grouped = {}
        for artifact in artifacts:
            file_type = artifact.file_type
            if file_type not in grouped:
                grouped[file_type] = []
            grouped[file_type].append(artifact)
        return grouped
    
    def _find_kernel_files(self) -> List[KernelArtifact]:
        """Find kernel files in standard locations"""
        artifacts = []
        locations = self._locate_kernel_storage()
        
        for location_path in locations.values():
            if os.path.exists(location_path):
                for root, dirs, files in os.walk(location_path):
                    for file in files:
                        file_path = os.path.join(root, file)
                        file_ext = os.path.splitext(file)[1]
                        
                        if file_ext in ['.py', '.cpp', '.cu', '.so', '.ttir', '.ttgir', '.cubin', '.ptx']:
                            try:
                                stat_info = os.stat(file_path)
                                artifact = KernelArtifact(
                                    path=file_path,
                                    file_type=file_ext,
                                    size_bytes=stat_info.st_size,
                                    creation_time=stat_info.st_mtime,
                                    content_summary=""
                                )
                                artifacts.append(artifact)
                            except OSError:
                                continue
        
        return artifacts
    
    def _analyze_python_kernel(self, file_path: str) -> Optional[Dict[str, Any]]:
        """Analyze a Python kernel file"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            # Basic analysis
            lines = content.count('\n')
            functions = content.count('def ')
            imports = content.count('import ')
            torch_ops = content.count('torch.')
            
            return {
                'path': file_path,
                'lines': lines,
                'functions': functions,
                'imports': imports,
                'torch_operations': torch_ops,
                'has_triton': 'triton' in content.lower()
            }
        except Exception:
            return None
    
    def _analyze_triton_kernel(self, file_path: str) -> Optional[Dict[str, Any]]:
        """Analyze a Triton kernel file"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            return {
                'path': file_path,
                'size_bytes': len(content),
                'is_ir': file_path.endswith(('.ttir', '.ttgir', '.llir')),
                'content_preview': content[:200] + '...' if len(content) > 200 else content
            }
        except Exception:
            return None
    
    def _analyze_cpp_kernel(self, file_path: str) -> Optional[Dict[str, Any]]:
        """Analyze a C++/CUDA kernel file"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            return {
                'path': file_path,
                'lines': content.count('\n'),
                'is_cuda': file_path.endswith('.cu'),
                'has_cuda_kernels': '__global__' in content,
                'includes': content.count('#include')
            }
        except Exception:
            return None
    
    def _analyze_binary_kernel(self, file_path: str) -> Optional[Dict[str, Any]]:
        """Analyze a binary kernel file"""
        try:
            size = os.path.getsize(file_path)
            return {
                'path': file_path,
                'size_bytes': size,
                'file_type': os.path.splitext(file_path)[1],
                'is_shared_library': file_path.endswith('.so'),
                'is_cuda_binary': file_path.endswith(('.cubin', '.ptx'))
            }
        except Exception:
            return None
    
    def _calculate_efficiency_metrics(self, kernel_stats: Dict[str, int], execution_time_ms: float) -> Dict[str, float]:
        """Calculate efficiency metrics"""
        total_kernels = kernel_stats.get('total_kernels', 0)
        
        if execution_time_ms <= 0 or total_kernels <= 0:
            return {'efficiency_score': 0.0, 'kernel_density': 0.0}
        
        # Simple efficiency metrics
        kernel_density = total_kernels / execution_time_ms
        efficiency_score = min(1.0, kernel_density / 10.0)  # Normalize to 0-1
        
        return {
            'efficiency_score': efficiency_score,
            'kernel_density': kernel_density
        }
    
    def _capture_environment_snapshot(self) -> Dict[str, str]:
        """Capture relevant environment variables"""
        relevant_vars = [
            'TORCH_COMPILE_DEBUG', 'TORCHINDUCTOR_CACHE_DIR', 'TORCH_LOGS',
            'TORCHINDUCTOR_VERBOSE', 'TORCHINDUCTOR_MAX_AUTOTUNE',
            'TORCHINDUCTOR_COORDINATE_DESCENT_TUNING', 'TORCHINDUCTOR_FREEZING',
            'TORCHINDUCTOR_FX_GRAPH_CACHE', 'TORCHINDUCTOR_FALLBACK_RANDOM'
        ]
        
        return {var: os.environ.get(var, 'Not set') for var in relevant_vars}
    
    def _print_exploration_summary(self, results: Dict[str, Any]):
        """Print comprehensive exploration summary"""
        print(f"\n📋 KERNEL EXPLORATION SUMMARY")
        print("=" * 50)
        
        # Compilation info
        comp_info = results['compilation_info']
        if comp_info['success']:
            print(f"✅ Compilation: Success ({comp_info['compilation_time_ms']:.1f}ms)")
        else:
            print(f"❌ Compilation: Failed - {comp_info['error']}")
        
        # Artifact summary
        artifact_info = results['artifact_analysis']
        print(f"📁 Artifacts: {artifact_info['total_files']} files found")
        print(f"📊 Storage locations: {len(artifact_info['storage_locations'])}")
        
        # Kernel summary
        kernel_info = results['kernel_analysis']
        if 'statistics' in kernel_info:
            stats = kernel_info['statistics']
            print(f"🧬 Kernels: {stats['total_kernels']} total")
            print(f"   Python: {stats['python_kernels']}")
            print(f"   Triton: {stats['triton_kernels']}")
            print(f"   C++/CUDA: {stats['cpp_kernels']}")
            print(f"   Binary: {stats['binary_kernels']}")
        
        # Performance summary
        perf_info = results['performance_analysis']
        if 'mean_execution_time_ms' in perf_info:
            print(f"⏱️ Performance: {perf_info['mean_execution_time_ms']:.3f}ms avg")
            print(f"📈 Efficiency: {perf_info['performance_efficiency']['efficiency_score']:.3f}")

# Initialize the production debugger
print("🚀 ProductionTorchInductorDebugger class defined and ready for use!")
production_debugger = ProductionTorchInductorDebugger(device=device, verbose=True)

🚀 ProductionTorchInductorDebugger class defined and ready for use!

🔧 Setting up environment for kernel exploration:
   TORCH_COMPILE_DEBUG = 1
   TORCHINDUCTOR_CACHE_DIR = /tmp/torchinductor_alibina (existing)
   TORCH_LOGS = +dynamo,+inductor,+graph_code
   TORCHINDUCTOR_VERBOSE = 1
   TORCHINDUCTOR_MAX_AUTOTUNE = 1
   TORCHINDUCTOR_COORDINATE_DESCENT_TUNING = 1
   TORCHINDUCTOR_FREEZING = 1
   TORCHINDUCTOR_FX_GRAPH_CACHE = 1
   TORCHINDUCTOR_FALLBACK_RANDOM = 0
🚀 ProductionTorchInductorDebugger initialized
   Device: cuda
   Debug artifacts: True
   Cache cleanup: True


### Systematic Kernel Exploration with ProductionTorchInductorDebugger

Now we'll use our **ProductionTorchInductorDebugger** class to perform comprehensive kernel exploration and analysis. This production-ready debugger integrates all the artifact inspection methods we built previously into a cohesive, automated workflow.

**Key Features:**
- ✅ **Automated Environment Setup**: Optimal environment variable configuration
- ✅ **Comprehensive Artifact Discovery**: Finds and categorizes all compilation artifacts  
- ✅ **Kernel Analysis**: Detailed analysis of Python, Triton, C++, and binary kernels
- ✅ **Performance Correlation**: Links artifacts to actual performance metrics
- ✅ **Production Ready**: Suitable for real development workflows

Let's explore different model complexities systematically:

In [46]:
def demo_simple_model_exploration():
    """Demonstrate systematic kernel exploration with a simple model"""
    
    print("🎯 DEMO 1: Simple Model Kernel Exploration")
    print("=" * 55)
    
    # Create a simple model for analysis
    class SimpleModel(nn.Module):
        def __init__(self, hidden_size=256):
            super().__init__()
            self.layers = nn.Sequential(
                nn.Linear(hidden_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size//2)
            )
        
        def forward(self, x):
            return self.layers(x)
    
    # Initialize model and input
    model = SimpleModel(hidden_size=256).to(device)
    input_tensor = torch.randn(32, 128, 256, device=device)
    
    print(f"📋 Model: SimpleModel")
    print(f"   Parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"   Input shape: {input_tensor.shape}")
    
    # Use ProductionTorchInductorDebugger for comprehensive analysis
    exploration_results = production_debugger.explore_compilation_artifacts(
        model=model,
        input_tensor=input_tensor,
        model_name="SimpleModel"
    )
    
    return exploration_results

# Execute the demonstration
simple_results = demo_simple_model_exploration()

🎯 DEMO 1: Simple Model Kernel Exploration
📋 Model: SimpleModel
   Parameters: 164,480
   Input shape: torch.Size([32, 128, 256])

🔍 SYSTEMATIC KERNEL EXPLORATION: SimpleModel

🧹 Cleaning compilation cache...


   ✅ Cleared cache directory: /tmp/torchinductor_alibina

📁 Located storage directories:
   debug_traces: ./torch_compile_debug
   additional_torch: /home/alibina/.cache/torch

⚙️ Compiling SimpleModel with artifact capture...
   ✅ Compilation successful in 8922.4ms

🔎 Discovering artifacts for SimpleModel...

📁 Located storage directories:
   primary_cache: /tmp/torchinductor_alibina
   debug_traces: ./torch_compile_debug
   additional_torchinductor_alibina: /tmp/torchinductor_alibina
   additional_torch: /home/alibina/.cache/torch
   📊 Found 46 artifacts across 4 locations
      .cubin: 4 files (0.03 MB)
      .json: 8 files (0.01 MB)
      .ttgir: 4 files (0.02 MB)
      .ptx: 4 files (0.04 MB)
      .ttir: 4 files (0.01 MB)
      .llir: 4 files (0.02 MB)
      .so: 2 files (0.04 MB)
      no_ext: 4 files (0.16 MB)
      .py: 4 files (0.02 MB)
      .best_config: 2 files (0.00 MB)
      .log: 4 files (0.00 MB)
      .6_sass_29437_3eb94150d986fdf056f52a9c214e66903d13e1d6: 1 files (0.

In [47]:
# Demo 2: Complex Model Exploration and Comparison
def demo_complex_model_exploration():
    """Demonstrate kernel exploration with a more complex model"""
    
    print("\n🎯 DEMO 2: Complex Model Kernel Exploration")
    print("=" * 55)
    
    # Create a more complex model (transformer-like)
    class ComplexModel(nn.Module):
        def __init__(self, hidden_size=512, num_layers=4):
            super().__init__()
            self.layers = nn.ModuleList()
            
            for _ in range(num_layers):
                layer = nn.Sequential(
                    nn.LayerNorm(hidden_size),
                    nn.Linear(hidden_size, hidden_size * 4),
                    nn.GELU(),
                    nn.Dropout(0.1),
                    nn.Linear(hidden_size * 4, hidden_size),
                    nn.Dropout(0.1)
                )
                self.layers.append(layer)
            
            self.final_norm = nn.LayerNorm(hidden_size)
            self.output_proj = nn.Linear(hidden_size, hidden_size // 2)
        
        def forward(self, x):
            for layer in self.layers:
                residual = x
                x = layer(x) + residual  # Residual connection
            x = self.final_norm(x)
            return self.output_proj(x)
    
    # Initialize complex model
    model = ComplexModel(hidden_size=512, num_layers=4).to(device)
    input_tensor = torch.randn(16, 256, 512, device=device)
    
    print(f"📋 Model: ComplexModel")
    print(f"   Parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"   Input shape: {input_tensor.shape}")
    print(f"   Layers: 4 transformer-like blocks")
    
    # Analyze with ProductionTorchInductorDebugger
    exploration_results = production_debugger.explore_compilation_artifacts(
        model=model,
        input_tensor=input_tensor,
        model_name="ComplexModel"
    )
    
    return exploration_results

# Demo 3: Comparative Analysis
def comparative_kernel_analysis(simple_results, complex_results):
    """Compare kernel exploration results between models"""
    
    print("\n🔬 COMPARATIVE KERNEL ANALYSIS")
    print("=" * 55)
    
    models = [
        ("SimpleModel", simple_results),
        ("ComplexModel", complex_results)
    ]
    
    print(f"{'Model':<15} {'Kernels':<10} {'Artifacts':<12} {'Perf (ms)':<12} {'Efficiency':<12}")
    print("-" * 65)
    
    for model_name, results in models:
        # Extract key metrics
        kernel_stats = results.get('kernel_analysis', {}).get('statistics', {})
        total_kernels = kernel_stats.get('total_kernels', 0)
        
        artifact_stats = results.get('artifact_analysis', {})
        total_artifacts = artifact_stats.get('total_files', 0)
        
        perf_stats = results.get('performance_analysis', {})
        exec_time = perf_stats.get('mean_execution_time_ms', 0)
        efficiency = perf_stats.get('performance_efficiency', {}).get('efficiency_score', 0)
        
        print(f"{model_name:<15} {total_kernels:<10} {total_artifacts:<12} {exec_time:<12.3f} {efficiency:<12.3f}")
    
    # Detailed breakdown
    print(f"\n📊 DETAILED BREAKDOWN")
    print("-" * 40)
    
    for model_name, results in models:
        print(f"\n{model_name}:")
        
        # Kernel breakdown
        kernel_stats = results.get('kernel_analysis', {}).get('statistics', {})
        print(f"   Kernels:")
        print(f"      Python: {kernel_stats.get('python_kernels', 0)}")
        print(f"      Triton: {kernel_stats.get('triton_kernels', 0)}")
        print(f"      C++/CUDA: {kernel_stats.get('cpp_kernels', 0)}")
        print(f"      Binary: {kernel_stats.get('binary_kernels', 0)}")
        
        # Compilation info
        comp_info = results.get('compilation_info', {})
        comp_time = comp_info.get('compilation_time_ms', 0)
        print(f"   Compilation: {comp_time:.1f}ms")
        
        # Storage locations
        storage_info = results.get('artifact_analysis', {}).get('storage_locations', {})
        print(f"   Storage locations: {len(storage_info)}")

# Execute complex model exploration
complex_results = demo_complex_model_exploration()

# Perform comparative analysis
comparative_kernel_analysis(simple_results, complex_results)


🎯 DEMO 2: Complex Model Kernel Exploration
📋 Model: ComplexModel
   Parameters: 8,535,296
   Input shape: torch.Size([16, 256, 512])
   Layers: 4 transformer-like blocks

🔍 SYSTEMATIC KERNEL EXPLORATION: ComplexModel

🧹 Cleaning compilation cache...
   ✅ Cleared cache directory: /tmp/torchinductor_alibina

📁 Located storage directories:
   debug_traces: ./torch_compile_debug
   additional_torch: /home/alibina/.cache/torch

⚙️ Compiling ComplexModel with artifact capture...
   ✅ Compilation successful in 13737.9ms

🔎 Discovering artifacts for ComplexModel...

📁 Located storage directories:
   primary_cache: /tmp/torchinductor_alibina
   debug_traces: ./torch_compile_debug
   additional_torchinductor_alibina: /tmp/torchinductor_alibina
   additional_torch: /home/alibina/.cache/torch
   📊 Found 137 artifacts across 4 locations
      .json: 28 files (0.03 MB)
      .ptx: 14 files (0.53 MB)
      .ttir: 14 files (0.31 MB)
      .ttgir: 14 files (0.33 MB)
      .llir: 14 files (0.53 MB)
   

In [48]:
# Advanced Kernel Inspection Utilities
def inspect_kernel_details(debugger_instance, model_name="SimpleModel"):
    """Advanced inspection of kernel details and artifacts"""
    
    print(f"\n🔬 ADVANCED KERNEL INSPECTION: {model_name}")
    print("=" * 55)
    
    # Get storage locations  
    locations = debugger_instance._locate_kernel_storage()
    
    print(f"📁 Active Storage Locations:")
    for name, path in locations.items():
        if os.path.exists(path):
            file_count = sum(len(files) for _, _, files in os.walk(path))
            total_size = sum(
                os.path.getsize(os.path.join(root, file))
                for root, _, files in os.walk(path)
                for file in files
                if os.path.exists(os.path.join(root, file))
            )
            print(f"   {name}: {file_count} files ({total_size/1024/1024:.2f} MB)")
            print(f"      Path: {path}")
    
    # Find and analyze recent kernel files
    print(f"\n🧬 Recent Kernel Files Analysis:")
    
    # Find Python kernels
    python_kernels = []
    triton_files = []
    binary_files = []
    
    for location_path in locations.values():
        if os.path.exists(location_path):
            for root, _, files in os.walk(location_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    
                    if file.endswith('.py') and 'kernel' in file.lower():
                        python_kernels.append(file_path)
                    elif file.endswith(('.ttir', '.ttgir', '.llir')):
                        triton_files.append(file_path)
                    elif file.endswith(('.so', '.cubin', '.ptx')):
                        binary_files.append(file_path)
    
    print(f"   Python kernels found: {len(python_kernels)}")
    print(f"   Triton IR files found: {len(triton_files)}")
    print(f"   Binary files found: {len(binary_files)}")
    
    # Show sample kernel content
    if python_kernels:
        print(f"\n📝 Sample Python Kernel Content:")
        sample_kernel = python_kernels[0]
        print(f"   File: {os.path.basename(sample_kernel)}")
        try:
            with open(sample_kernel, 'r') as f:
                content = f.read(1000)  # First 1000 chars
                lines = content.split('\n')[:20]  # First 20 lines
                for i, line in enumerate(lines, 1):
                    print(f"   {i:2d}: {line}")
                if len(content) > 1000:
                    print("   ... (truncated)")
        except Exception as e:
            print(f"   Error reading file: {e}")
    
    # Environment verification
    print(f"\n🔧 Environment Verification:")
    important_vars = [
        'TORCH_COMPILE_DEBUG',
        'TORCHINDUCTOR_VERBOSE', 
        'TORCH_LOGS',
        'TORCHINDUCTOR_MAX_AUTOTUNE'
    ]
    
    for var in important_vars:
        value = os.environ.get(var, 'Not set')
        status = "✅" if value != 'Not set' else "⚠️"
        print(f"   {status} {var}: {value}")
    
    return {
        'locations': locations,
        'python_kernels': len(python_kernels),
        'triton_files': len(triton_files),
        'binary_files': len(binary_files),
        'sample_kernel': python_kernels[0] if python_kernels else None
    }

# Performance vs Complexity Analysis
def analyze_performance_complexity_correlation(simple_results, complex_results):
    """Analyze correlation between model complexity and performance"""
    
    print(f"\n📈 PERFORMANCE vs COMPLEXITY CORRELATION")
    print("=" * 55)
    
    # Extract metrics
    models_data = [
        {
            'name': 'SimpleModel',
            'results': simple_results,
            'complexity_score': 1.0  # Base complexity
        },
        {
            'name': 'ComplexModel', 
            'results': complex_results,
            'complexity_score': 3.5  # Higher complexity
        }
    ]
    
    print(f"{'Model':<15} {'Complexity':<12} {'Kernels':<10} {'Exec(ms)':<12} {'Comp(ms)':<12} {'Efficiency':<12}")
    print("-" * 80)
    
    for model_data in models_data:
        name = model_data['name']
        complexity = model_data['complexity_score']
        results = model_data['results']
        
        # Extract metrics
        kernel_stats = results.get('kernel_analysis', {}).get('statistics', {})
        kernels = kernel_stats.get('total_kernels', 0)
        
        perf_stats = results.get('performance_analysis', {})
        exec_time = perf_stats.get('mean_execution_time_ms', 0)
        
        comp_info = results.get('compilation_info', {})
        comp_time = comp_info.get('compilation_time_ms', 0)
        
        efficiency = perf_stats.get('performance_efficiency', {}).get('efficiency_score', 0)
        
        print(f"{name:<15} {complexity:<12.1f} {kernels:<10} {exec_time:<12.3f} {comp_time:<12.1f} {efficiency:<12.3f}")
    
    # Calculate correlations
    print(f"\n📊 Correlation Analysis:")
    
    simple_perf = simple_results.get('performance_analysis', {})
    complex_perf = complex_results.get('performance_analysis', {})
    
    simple_exec = simple_perf.get('mean_execution_time_ms', 0)
    complex_exec = complex_perf.get('mean_execution_time_ms', 0)
    
    simple_kernels = simple_results.get('kernel_analysis', {}).get('statistics', {}).get('total_kernels', 0)
    complex_kernels = complex_results.get('kernel_analysis', {}).get('statistics', {}).get('total_kernels', 0)
    
    if simple_exec > 0 and complex_exec > 0:
        perf_ratio = complex_exec / simple_exec
        kernel_ratio = complex_kernels / simple_kernels if simple_kernels > 0 else 0
        
        print(f"   Performance degradation: {perf_ratio:.2f}x")
        print(f"   Kernel count increase: {kernel_ratio:.2f}x")
        print(f"   Complexity scaling factor: {perf_ratio/3.5:.2f}")
        
        # Efficiency assessment
        if perf_ratio < 2.0:
            print(f"   ✅ Good scaling: Performance scales well with complexity")
        elif perf_ratio < 4.0:
            print(f"   ⚠️ Moderate scaling: Some optimization opportunities")
        else:
            print(f"   ❌ Poor scaling: Significant optimization needed")

# Execute advanced inspection
kernel_details = inspect_kernel_details(production_debugger, "SimpleModel")

# Execute performance analysis
analyze_performance_complexity_correlation(simple_results, complex_results)


🔬 ADVANCED KERNEL INSPECTION: SimpleModel

📁 Located storage directories:
   primary_cache: /tmp/torchinductor_alibina
   debug_traces: ./torch_compile_debug
   additional_torchinductor_alibina: /tmp/torchinductor_alibina
   additional_torch: /home/alibina/.cache/torch
📁 Active Storage Locations:
   primary_cache: 112 files (3.44 MB)
      Path: /tmp/torchinductor_alibina
   debug_traces: 6 files (0.00 MB)
      Path: ./torch_compile_debug
   additional_torchinductor_alibina: 112 files (3.44 MB)
      Path: /tmp/torchinductor_alibina
   additional_torch: 2 files (0.11 MB)
      Path: /home/alibina/.cache/torch

🧬 Recent Kernel Files Analysis:
   Python kernels found: 0
   Triton IR files found: 72
   Binary files found: 68

🔧 Environment Verification:
   ✅ TORCH_COMPILE_DEBUG: 1
   ✅ TORCHINDUCTOR_VERBOSE: 1
   ✅ TORCH_LOGS: +dynamo,+inductor,+graph_code
   ✅ TORCHINDUCTOR_MAX_AUTOTUNE: 1

📈 PERFORMANCE vs COMPLEXITY CORRELATION
Model           Complexity   Kernels    Exec(ms)     Com

## 🎯 Production Best Practices and Recommendations

Based on our systematic kernel exploration, here are the key insights and best practices:

### 📊 Key Findings

1. **Kernel Generation**: Complex models generate significantly more kernels (82 vs 22)
2. **Performance Scaling**: 43.5x performance degradation for 3.5x complexity increase
3. **Compilation Overhead**: Complex models take 54% longer to compile (13.7s vs 8.9s)
4. **Storage Impact**: 112 artifacts generated, 3.44 MB cache usage

### ✅ Recommended Workflow

**For Development:**
```python
# 1. Initialize debugger with optimal settings
debugger = ProductionTorchInductorDebugger(
    device='cuda',
    cache_cleanup=True,
    debug_artifacts=True,
    verbose=True
)

# 2. Systematic exploration
results = debugger.explore_compilation_artifacts(
    model=your_model,
    input_tensor=sample_input,
    model_name="YourModel"
)

# 3. Analyze results for optimization opportunities
```

**For Production:**
- Set `debug_artifacts=False` to reduce overhead
- Use `cache_cleanup=False` for persistent caching
- Monitor artifact storage growth in deployment

### 🚀 Optimization Strategies

1. **Model Architecture**: Consider simpler architectures for better kernel efficiency
2. **Input Sizing**: Optimize batch sizes and sequence lengths  
3. **Compilation Strategy**: Use mode='max-autotune' for performance-critical paths
4. **Cache Management**: Implement artifact cleanup in production pipelines

### 📈 Performance Monitoring

Use the ProductionTorchInductorDebugger to:
- Track kernel count growth over model iterations
- Monitor compilation time vs execution time ratios
- Identify optimization regressions early in development
- Correlate artifact patterns with performance metrics

In [49]:
# 🎯 COMPLETE WORKFLOW SUMMARY
print("🎯 SYSTEMATIC KERNEL EXPLORATION - COMPLETE WORKFLOW")
print("=" * 65)

print("\n✅ Environment Setup:")
print("   - TORCH_COMPILE_DEBUG=1 ✓")
print("   - TORCHINDUCTOR_VERBOSE=1 ✓") 
print("   - TORCH_LOGS=+dynamo,+inductor,+graph_code ✓")
print("   - TORCHINDUCTOR_MAX_AUTOTUNE=1 ✓")

print("\n✅ ProductionTorchInductorDebugger Features:")
print("   - Automated environment configuration ✓")
print("   - Comprehensive artifact discovery ✓") 
print("   - Kernel analysis (Python, Triton, C++, Binary) ✓")
print("   - Performance correlation analysis ✓")
print("   - Production-ready workflows ✓")

print("\n✅ Analysis Results:")
print("   - SimpleModel: 22 kernels, 3.74ms execution")
print("   - ComplexModel: 82 kernels, 162.67ms execution") 
print("   - Performance scaling factor: 12.43 (needs optimization)")
print("   - Total artifacts generated: 112 files (3.44 MB)")

print("\n✅ Key Insights:")
print("   - Kernel count correlates with model complexity")
print("   - Compilation time increases with complexity") 
print("   - Cache management is critical for production")
print("   - Systematic exploration enables optimization")

print("\n🚀 Ready for Production Use!")
print("   Use ProductionTorchInductorDebugger for:")
print("   • Model optimization analysis")
print("   • Performance regression detection") 
print("   • Compilation pipeline debugging")
print("   • Production deployment preparation")

# Verification that all components are working
print("\n🔧 System Verification:")
print(f"   Device: {device}")
print(f"   PyTorch version: {torch.__version__}")
print(f"   CUDA available: {torch.cuda.is_available()}")
print(f"   Production debugger initialized: {production_debugger is not None}")
print(f"   Exploration results available: {len([simple_results, complex_results])} models analyzed")

print("\n✨ Systematic Kernel Exploration Complete! ✨")

🎯 SYSTEMATIC KERNEL EXPLORATION - COMPLETE WORKFLOW

✅ Environment Setup:
   - TORCH_COMPILE_DEBUG=1 ✓
   - TORCHINDUCTOR_VERBOSE=1 ✓
   - TORCH_LOGS=+dynamo,+inductor,+graph_code ✓
   - TORCHINDUCTOR_MAX_AUTOTUNE=1 ✓

✅ ProductionTorchInductorDebugger Features:
   - Automated environment configuration ✓
   - Comprehensive artifact discovery ✓
   - Kernel analysis (Python, Triton, C++, Binary) ✓
   - Performance correlation analysis ✓
   - Production-ready workflows ✓

✅ Analysis Results:
   - SimpleModel: 22 kernels, 3.74ms execution
   - ComplexModel: 82 kernels, 162.67ms execution
   - Performance scaling factor: 12.43 (needs optimization)
   - Total artifacts generated: 112 files (3.44 MB)

✅ Key Insights:
   - Kernel count correlates with model complexity
   - Compilation time increases with complexity
   - Cache management is critical for production
   - Systematic exploration enables optimization

🚀 Ready for Production Use!
   Use ProductionTorchInductorDebugger for:
   • Model

### 📊 Step 2: File Type Analysis

Now let's categorize the files we find to understand what types of artifacts PyTorch generates. Different file types serve different purposes in the compilation pipeline.

In [43]:
def analyze_file_types(locations_found):
    """
    Step 2: Analyze and categorize file types
    """
    print(f"\n📊 Step 2: File Type Analysis")
    print("-" * 30)
    
    all_files = []
    
    # Collect all files from found locations
    for location_name, location_path in locations_found:
        print(f"\n   📍 Analyzing: {location_name} ({location_path})")
        
        # Recursively find all files
        for root, dirs, files in os.walk(location_path):
            for file in files:
                full_path = os.path.join(root, file)
                try:
                    file_size = os.path.getsize(full_path)
                    all_files.append({
                        'path': full_path,
                        'name': file,
                        'size': file_size,
                        'location': location_name,
                        'extension': os.path.splitext(file)[1]
                    })
                except OSError:
                    print(f"      Could not access {full_path}, skipping.")

    if not all_files:
        print("   No files found in the explored locations.")
        return {'total_files': 0, 'file_categories': {}}
        
    # Categorize files by extension
    file_categories = {}
    for file_info in all_files:
        ext = file_info['extension']
        if ext not in file_categories:
            file_categories[ext] = []
        file_categories[ext].append(file_info)
    
    print(f"\n   📈 File Type Summary:")
    for ext, files_in_ext in sorted(file_categories.items()):
        total_size = sum(f['size'] for f in files_in_ext)
        print(f"      {ext or '(no ext)'}: {len(files_in_ext)} files, {total_size/1024:.1f} KB total")
    
    return {'total_files': len(all_files), 'file_categories': file_categories}

# Execute step 2 if we found locations
if locations_found:
    file_analysis = analyze_file_types(locations_found)
else:
    print("Skipping file analysis - no locations found.")
    file_analysis = {'total_files': 0, 'file_categories': {}}


📊 Step 2: File Type Analysis
------------------------------

   📍 Analyzing: Primary Cache (/tmp/torchinductor_alibina)

   📍 Analyzing: Debug Traces (./torch_compile_debug)

   📈 File Type Summary:
      (no ext): 5 files, 145.0 KB total
      .best_config: 2 files, 0.4 KB total
      .cubin: 11 files, 142.7 KB total
      .json: 22 files, 22.8 KB total
      .llir: 11 files, 204.2 KB total
      .log: 3 files, 0.0 KB total
      .ptx: 11 files, 165.3 KB total
      .py: 6 files, 24.8 KB total
      .so: 3 files, 63.5 KB total
      .ttgir: 11 files, 62.7 KB total
      .ttir: 11 files, 55.5 KB total


### 🐍 Step 3: Python/Triton Kernel Analysis

The most valuable artifacts for understanding optimizations are the Python files containing generated Triton kernel source code. Let's examine these files to understand what PyTorch generates.

In [17]:
def analyze_triton_patterns(content):
    """Analyze Triton-specific patterns in kernel source"""
    patterns = {
        '@triton.jit': content.count('@triton.jit'),
        'tl.program_id': content.count('tl.program_id'),
        'tl.load': content.count('tl.load'),
        'tl.store': content.count('tl.store'),
        'BLOCK_SIZE': content.count('BLOCK_SIZE'),
        'tl.arange': content.count('tl.arange'),
        'tl.where': content.count('tl.where'),
        'triton.language': content.count('triton.language'),
        'autotuned': content.count('autotuned')
    }
    return patterns

def check_optimization_patterns(content):
    """Check for common optimization patterns in generated kernels"""
    content_lower = content.lower()
    indicators = []
    
    if 'fused' in content_lower or 'fusion' in content_lower:
        indicators.append("Operation Fusion Likely")
    
    if 'block_size' in content_lower:
        indicators.append("Block Size Optimization")
    
    if 'autotuned' in content_lower or 'autotune' in content_lower:
        indicators.append("Autotuned Parameters")
    
    if 'tl.load' in content_lower and 'tl.store' in content_lower:
        indicators.append("Optimized Memory Access")
    
    if any(block in content_lower for block in ['xblock', 'yblock', 'zblock']):
        indicators.append("Multi-dimensional Blocking")
    
    if 'persistent_reduction' in content_lower:
        indicators.append("Persistent Reduction Optimization")
        
    if 'softmax' in content_lower and 'online' in content_lower:
        indicators.append("Online Softmax Optimization")

    return indicators

print("🔧 Helper functions defined for kernel analysis")

🔧 Helper functions defined for kernel analysis


In [18]:
def analyze_python_kernels(file_categories):
    """
    Step 3: Examine Python/Triton kernel files
    """
    print(f"\n🐍 Step 3: Python/Triton Kernel Analysis")
    print("-" * 30)
    
    python_files = file_categories.get('.py', [])
    
    if python_files:
        # Find substantial kernel files (heuristic: size > 200 bytes)
        substantial_kernels = [f for f in python_files if f['size'] > 200]
        
        if substantial_kernels:
            # Analyze the largest kernel file as an example
            largest_kernel = max(substantial_kernels, key=lambda x: x['size'])
            
            print(f"   📄 Analyzing example kernel: {os.path.basename(largest_kernel['path'])}")
            print(f"      Location: {largest_kernel['path']}")
            print(f"      Size: {largest_kernel['size']} bytes")
            
            try:
                with open(largest_kernel['path'], 'r') as f_kernel:
                    content = f_kernel.read()
                
                lines = content.split('\n')
                
                print(f"\n   📝 Kernel Source Preview (first 25 lines):")
                print("   " + "─" * 70)
                
                for i, line in enumerate(lines[:25], 1):
                    print(f"   {i:2d}: {line}")
                
                if len(lines) > 25:
                    print(f"   ... ({len(lines) - 25} more lines)")
                
                # Analyze Triton-specific patterns
                triton_analysis = analyze_triton_patterns(content)
                
                print(f"\n   🎯 Triton Pattern Analysis:")
                for pattern, count in triton_analysis.items():
                    if count > 0:
                        print(f"      {pattern}: {count} occurrences")
                
                # Check for optimization indicators
                optimization_indicators = check_optimization_patterns(content)
                
                if optimization_indicators:
                    print(f"\n   ⚡ Optimization Patterns Detected:")
                    for indicator in optimization_indicators:
                        print(f"      ✅ {indicator}")
                else:
                    print(f"\n   ℹ️  No obvious optimization patterns detected")
                    
                return True
                    
            except Exception as e:
                print(f"   ❌ Could not analyze kernel {largest_kernel['path']}: {e}")
                return False
        else:
            print(f"   ℹ️  Found {len(python_files)} Python files, but none are substantial kernels")
            return False
    else:
        print(f"   ⚠️  No Python (.py) kernel files found")
        return False

# Execute step 3 if we have file categories
if file_analysis['total_files'] > 0:
    kernel_analysis_success = analyze_python_kernels(file_analysis['file_categories'])
else:
    print("Skipping kernel analysis - no files found.")
    kernel_analysis_success = False


🐍 Step 3: Python/Triton Kernel Analysis
------------------------------
   📄 Analyzing example kernel: cnkhj4tktdnkzkdsqpsxdu4mz6ia2yzdtrm4j6kyjfqnvdbicd6s.py
      Location: /tmp/torchinductor_alibina/nk/cnkhj4tktdnkzkdsqpsxdu4mz6ia2yzdtrm4j6kyjfqnvdbicd6s.py
      Size: 40907 bytes

   📝 Kernel Source Preview (first 25 lines):
   ──────────────────────────────────────────────────────────────────────
    1: # AOT ID: ['8_inference']
    2: from ctypes import c_void_p, c_long, c_int
    3: import torch
    4: import math
    5: import random
    6: import os
    7: import tempfile
    8: from math import inf, nan
    9: from torch._inductor.hooks import run_intermediate_hooks
   10: from torch._inductor.utils import maybe_profile
   11: from torch._inductor.codegen.memory_planning import _align as align
   12: from torch import device, empty_strided
   13: from torch._inductor.async_compile import AsyncCompile
   14: from torch._inductor.select_algorithm import extern_kernels
   15: fr

### 📊 Step 4: Performance Artifacts Analysis

Beyond source code, PyTorch generates binary kernels and metadata files. These artifacts represent the final compiled kernels and provide insights into the compilation pipeline's output.

In [19]:
def analyze_performance_artifacts(file_categories):
    """
    Step 4: Analyze binary kernels and metadata
    """
    print(f"\n📊 Step 4: Other Performance Artifacts")
    print("-" * 30)
    
    # Look for binary kernels
    binary_files = []
    for ext in ['.so', '.cubin', '.ptx']:  # Different binary formats
        binary_files.extend(file_categories.get(ext, []))
    
    if binary_files:
        print(f"   🔧 Found {len(binary_files)} compiled binary files:")
        for binary_info in binary_files[:5]:  # Show first 5
            print(f"      📦 {os.path.basename(binary_info['path'])} " +
                  f"({binary_info['size']} bytes, {binary_info['extension']})")
        if len(binary_files) > 5:
            print(f"      ... and {len(binary_files) - 5} more")
    else:
        print(f"   ℹ️  No compiled binary files (.so, .cubin, .ptx) found")
    
    # Look for metadata
    json_files = file_categories.get('.json', [])
    if json_files:
        print(f"\n   📋 Found {len(json_files)} metadata (.json) files")
        # Try to read one for insights
        try:
            with open(json_files[0]['path'], 'r') as f_json:
                metadata = json.load(f_json)
            print(f"      📝 Sample metadata keys: {list(metadata.keys())}")
        except Exception as e:
            print(f"      ℹ️  Metadata file present but could not read: {e}")
    
    return {
        'binary_files_found': len(binary_files),
        'metadata_files_found': len(json_files)
    }

# Execute step 4 if we have file categories
if file_analysis['total_files'] > 0:
    artifacts_analysis = analyze_performance_artifacts(file_analysis['file_categories'])
else:
    print("Skipping artifacts analysis - no files found.")
    artifacts_analysis = {'binary_files_found': 0, 'metadata_files_found': 0}


📊 Step 4: Other Performance Artifacts
------------------------------
   🔧 Found 675 compiled binary files:
      📦 c3jlznrgpr2bjk6cv4zubdn5t7tuzunyzki3ds3jx3enxxymvry2.so (44624 bytes, .so)
      📦 __triton_launcher.so (17328 bytes, .so)
      📦 __triton_launcher.so (21424 bytes, .so)
      📦 __triton_launcher.so (21672 bytes, .so)
      📦 __triton_launcher.so (17328 bytes, .so)
      ... and 670 more

   📋 Found 628 metadata (.json) files
      📝 Sample metadata keys: ['child_paths']


### 🎓 Kernel Exploration Summary and Insights

Let's summarize what we've discovered about PyTorch's compilation artifacts and what they tell us about the optimization process.

In [20]:
# Final summary of kernel exploration
if file_analysis['total_files'] > 0:
    print("🎓 Kernel Exploration Summary:")
    print(f"   📊 Total artifacts analyzed: {file_analysis['total_files']}")
    
    python_kernels = len(file_analysis['file_categories'].get('.py', []))
    print(f"   🐍 Python kernels found: {python_kernels}")
    print(f"   🔧 Binary kernels found: {artifacts_analysis['binary_files_found']}")
    print(f"   📋 Metadata files found: {artifacts_analysis['metadata_files_found']}")
    
    print(f"\n💡 Key Insights:")
    print(f"   • Generated kernels reveal PyTorch's optimization strategies")
    print(f"   • Source code shows fusion opportunities and memory access patterns")
    print(f"   • Binary artifacts represent final optimized kernel implementations")
    print(f"   • Understanding these artifacts helps debug performance issues")
    
    print(f"\n🔬 Next Steps for Deeper Analysis:")
    print(f"   • Compare kernels across different input sizes")
    print(f"   • Examine autotuning parameter choices")
    print(f"   • Profile kernel execution times")
    print(f"   • Study memory access patterns in kernel source")
    
else:
    print("ℹ️ Kernel exploration did not find artifacts.")
    print("   • Ensure torch.compile() has been used in this session")
    print("   • Check if compilation was successful")
    print("   • Try enabling TORCH_COMPILE_DEBUG=1 for debug traces")

🎓 Kernel Exploration Summary:
   📊 Total artifacts analyzed: 2995
   🐍 Python kernels found: 503
   🔧 Binary kernels found: 675
   📋 Metadata files found: 628

💡 Key Insights:
   • Generated kernels reveal PyTorch's optimization strategies
   • Source code shows fusion opportunities and memory access patterns
   • Binary artifacts represent final optimized kernel implementations
   • Understanding these artifacts helps debug performance issues

🔬 Next Steps for Deeper Analysis:
   • Compare kernels across different input sizes
   • Examine autotuning parameter choices
   • Profile kernel execution times
   • Study memory access patterns in kernel source



### 🔬 Systematic Kernel Exploration and Analysis {#kernel-exploration}

Understanding the kernels generated by `torch.compile` is crucial for deep performance analysis and debugging. This section details how to locate, examine, and interpret these kernels and other compilation artifacts. By exploring these files, you can gain insights into how PyTorch optimizes your code at a low level.


## Understanding Performance with `torch.compile()`

Effective use of `torch.compile()` hinges on understanding when it provides a net benefit. The primary trade-off is the initial compilation time versus the accumulated execution time savings over multiple runs.

### 📊 The Performance Equation

The total benefit of compilation can be expressed as:

```
Total Time Saved = (Baseline Time - Optimized Time) × Number of Runs - Compilation Time
```
The **break-even point** is the number of runs required for the compiled version to become faster overall:
```
Break-even point (Number of Runs) = Compilation Time ÷ (Baseline Time - Optimized Time)
```

### 🎯 Key Factors Affecting Performance

1.  **Model Complexity**: More operations generally lead to more fusion opportunities and better speedups.
2.  **Input Size**: Larger tensors can better amortize fixed overheads of GPU kernel launches.
3.  **Operation Types**: Some operations (e.g., element-wise, reductions) benefit more from fusion than others.
4.  **Hardware**: The specific GPU (or CPU) capabilities influence potential optimizations.
5.  **Graph Breaks**: Frequent graph breaks can diminish or negate performance gains.

### 💡 When Compilation Helps Most

-   **Training loops**: Many iterations amortize compilation cost effectively.
-   **Large models**: More operations to optimize and fuse.
-   **Inference servers**: Repeated execution of the same model.
-   **Models with many fusible operations**: Sequences of element-wise operations, normalizations, activations.

### ⚠️ When to Be Cautious

-   **Single-shot inference**: Compilation overhead may outweigh execution time savings.
-   **Very simple operations/models**: Overhead might exceed benefits.
-   **Highly dynamic input shapes**: Can lead to frequent recompilations if not handled with `dynamic=True` or shape specialization.
-   **Memory-constrained environments**: Compilation itself consumes memory.

## Performance Patterns and Optimization Strategies

Beyond basic break-even analysis, consider these strategies:

#### Strategy 1: Warm-up and Caching
Compile the model once during initialization (e.g., with dummy data) so subsequent calls use the cached, optimized version.
```python
# During model initialization
# model = MyModel() # Define your model
# compiled_model = torch.compile(model)

# Warm-up with typical input to trigger compilation and caching
# dummy_input = torch.randn(typical_batch_size, ..., device=device) # Define your dummy input
# _ = compiled_model(dummy_input)

# Now ready for production use with optimized kernels
```
*(Code commented out as it's illustrative)*

#### Strategy 2: Selective Compilation
Apply `torch.compile()` only to performance-critical parts of your model or specific execution paths.
```python
# class MyModel(nn.Module):
#     def __init__(self):
#         super().__init__()
#         # Compile only the critical part
#         self.critical_block = torch.compile(self._critical_computation)
#         # Other parts might remain uncompiled
#         self.non_critical_block = self._non_critical_computation

#     def _critical_computation(self, x):
#         # ... performance-sensitive operations ...
#         return x

#     def _non_critical_computation(self, x):
#         # ... less sensitive or problematic operations ...
#         return x

#     def forward(self, x):
#         x = self.critical_block(x)
#         x = self.non_critical_block(x)
#         return x
```
*(Code commented out as it's illustrative. Note: `torch.compile` on a module method will compile it for the specific instance. If compiling a submodule, assign the compiled submodule.)*

#### Strategy 3: Understanding Compilation Modes
PyTorch offers different compilation modes (`default`, `reduce-overhead`, `max-autotune`) that trade compilation time for runtime performance. `max-autotune` takes longer to compile but may yield faster kernels. `reduce-overhead` compiles faster, useful if compilation time is critical.

## 2.3 Performance Benchmarking: Systematic Optimization Analysis {#performance-benchmarking}

To truly understand the impact of `torch.compile()`, systematic and statistically sound benchmarking is essential. This involves:

#### **Multi-Dimensional Analysis**
-   **Model Complexity**: Testing from simple operations to complex neural networks.
-   **Input Scale**: Evaluating various tensor sizes and batch dimensions.
-   **Hardware Utilization**: Observing GPU memory and compute efficiency.
-   **Compilation Modes**: Comparing `default`, `reduce-overhead`, and `max-autotune`.

#### **Statistical Rigor**
-   **Multiple Measurements**: Averaging over several runs to account for variance.
-   **Warmup Runs**: Excluding initial runs that might include one-off costs.
-   **Variance Analysis**: Understanding performance consistency (e.g., standard deviation).
-   **Confidence Intervals**: Quantifying the uncertainty in measurements.

The following `AdvancedBenchmarkSuite` provides a framework for such analysis.

## 2.3 Performance Benchmarking: Systematic Optimization Analysis {#performance-benchmarking}

To truly understand the impact of `torch.compile()`, systematic and statistically sound benchmarking is essential. This involves:

#### **Multi-Dimensional Analysis**
-   **Model Complexity**: Testing from simple operations to complex neural networks.
-   **Input Scale**: Evaluating various tensor sizes and batch dimensions.
-   **Hardware Utilization**: Observing GPU memory and compute efficiency.
-   **Compilation Modes**: Comparing `default`, `reduce-overhead`, and `max-autotune`.

#### **Statistical Rigor**
-   **Multiple Measurements**: Averaging over several runs to account for variance.
-   **Warmup Runs**: Excluding initial runs that might include one-off costs.
-   **Variance Analysis**: Understanding performance consistency (e.g., standard deviation).
-   **Confidence Intervals**: Quantifying the uncertainty in measurements.

The following `AdvancedBenchmarkSuite` provides a framework for such analysis.


In [21]:
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import statistics
import numpy as np

# Ensure the device is set
device = "cuda" if torch.cuda.is_available() else "cpu"

### 🧪 Comprehensive Performance Benchmarking Framework

class AdvancedBenchmarkSuite:
    """
    Professional-grade benchmarking suite for torch.compile() performance analysis
    """
    
    def __init__(self, device=device, num_trials=20, warmup_trials=5):
        self.device = device
        self.num_trials = num_trials
        self.warmup_trials = warmup_trials
        self.results = {}
        
    def benchmark_model_complexity(self):
        """Analyze performance across different model complexities"""
        
        print("🧪 MODEL COMPLEXITY ANALYSIS")
        print("=" * 40)
        
        # Define test models of increasing complexity
        # Shapes are (sequence_length, hidden_size) for input tensor (batch_size, seq_len, hidden_size)
        test_configurations = [
            ("Simple Ops", self._create_simple_model, (128, 256)), # input_shape for features
            ("Medium Model", self._create_medium_model, (256, 512)), 
            ("Complex Model", self._create_complex_model, (512, 1024)),
            ("Very Complex", self._create_very_complex_model, (256, 2048)) # Example: smaller seq_len, larger hidden
        ]
        
        complexity_results_list = [] # Renamed for clarity
        
        for config_name, model_factory, model_input_features_shape in test_configurations:
            print(f"\n🔬 Testing: {config_name}")
            # Assuming a fixed batch size for these tests, e.g., 16
            batch_size = 16 
            actual_input_shape = (batch_size, *model_input_features_shape)
            print(f"   Model Input Features Shape (SeqLen, Hidden): {model_input_features_shape}")
            print(f"   Actual Tensor Shape (Batch, SeqLen, Hidden): {actual_input_shape}")
            
            # Create model and test data
            model = model_factory(model_input_features_shape[1]).to(self.device) # Pass hidden_size to factory
            test_input = torch.randn(actual_input_shape, device=self.device)
            
            # Benchmark this configuration
            result_stats = self._benchmark_single_config(model, test_input, config_name) # Renamed
            complexity_results_list.append(result_stats)
            
            # Print immediate results
            self._print_benchmark_result(result_stats)
        
        # Analyze complexity trends
        self._analyze_complexity_trends(complexity_results_list)
        return complexity_results_list
    
    def benchmark_compilation_modes(self):
        """Compare different torch.compile() modes"""
        
        print(f"\n🎯 COMPILATION MODES COMPARISON")
        print("=" * 40)
        
        # Test model - using medium model as a standard test case
        # Define a standard input shape for this comparison
        medium_model_hidden_size = 512
        medium_model_input_shape = (16, 256, medium_model_hidden_size) # Batch, Seq, Hidden
        
        model = self._create_medium_model(medium_model_hidden_size).to(self.device)
        test_input = torch.randn(medium_model_input_shape, device=self.device)
        print(f"   Using Medium Model (Hidden: {medium_model_hidden_size}) with input {medium_model_input_shape}")

        compilation_modes_to_test = [ # Renamed
            ("default", {"mode": "default"}),
            ("reduce-overhead", {"mode": "reduce-overhead"}),
            ("max-autotune", {"mode": "max-autotune"}),
        ]
        
        mode_results_list = [] # Renamed
        
        # Baseline for comparison (uncompiled)
        print(f"\n⚙️  Measuring baseline (uncompiled) for mode comparison...")
        baseline_times = self._measure_baseline(model, test_input)
        baseline_mean_ms = statistics.mean(baseline_times) * 1000
        baseline_std_ms = statistics.stdev(baseline_times) * 1000 if len(baseline_times) > 1 else 0
        print(f"   📊 Baseline: {baseline_mean_ms:.3f}ms ± {baseline_std_ms:.3f}ms")

        for mode_name, compile_config in compilation_modes_to_test:
            print(f"\n⚙️  Testing mode: {mode_name}")
            
            # Benchmark this mode
            torch._dynamo.reset() # Reset cache for each mode
            
            # Measure compilation time separately for modes
            compile_start_time = time.perf_counter()
            compiled_model = torch.compile(model, **compile_config)
            # First inference to ensure compilation finishes
            with torch.no_grad():
                _ = compiled_model(test_input) 
            if torch.cuda.is_available(): torch.cuda.synchronize()
            compilation_duration_ms = (time.perf_counter() - compile_start_time) * 1000
            print(f"   Compilation time for mode '{mode_name}': {compilation_duration_ms:.1f} ms")

            result_stats = self._benchmark_compiled_model(compiled_model, test_input, f"mode_{mode_name}")
            result_stats['mode'] = mode_name
            result_stats['compilation_ms'] = compilation_duration_ms # Add compilation time to results
            result_stats['baseline_mean_ms_for_speedup'] = baseline_mean_ms # For speedup calculation against common baseline
            mode_results_list.append(result_stats)
            
            print(f"   📊 {mode_name} (Optimized): {result_stats['optimized_mean_ms']:.3f}ms ± {result_stats['optimized_std_ms']:.3f}ms")
        
        self._analyze_mode_comparison(mode_results_list, baseline_mean_ms)
        return mode_results_list
    
    def benchmark_input_scaling(self):
        """Analyze performance scaling with input size"""
        
        print(f"\n📈 INPUT SCALING ANALYSIS")
        print("=" * 40)
        
        # Using medium model structure, vary hidden_size and seq_len
        medium_model_base_hidden_size = 512 # For _create_medium_model
        
        # Different input scales (SeqLen, HiddenSize)
        input_scales_to_test = [ # Renamed
            (64, 256),   # Small
            (128, 512),  # Medium
            (256, 1024), # Large
            (512, 2048), # Very Large
        ]
        
        scaling_results_list = [] # Renamed
        batch_size = 8 # Fixed batch size for scaling test

        for seq_len, hidden_size in input_scales_to_test:
            scale_name = f"B{batch_size}_S{seq_len}_H{hidden_size}" # More descriptive name
            print(f"\n📏 Testing scale: {scale_name}")
            
            try:
                model_instance = self._create_medium_model(hidden_size).to(self.device) # Create model with current hidden_size
                test_input = torch.randn(batch_size, seq_len, hidden_size, device=self.device)
                
                torch._dynamo.reset() # Reset cache for each scale config
                compiled_model = torch.compile(model_instance) # Compile with default mode
                
                result_stats = self._benchmark_compiled_model(compiled_model, test_input, f"scale_{scale_name}")
                result_stats['scale_config'] = {'batch': batch_size, 'seq_len': seq_len, 'hidden_size': hidden_size} # Store scale config
                result_stats['total_elements'] = batch_size * seq_len * hidden_size
                scaling_results_list.append(result_stats)
                
                print(f"   📊 {scale_name} (Optimized): {result_stats['optimized_mean_ms']:.3f}ms")
                
            except RuntimeError as e:
                print(f"   ❌ Scale {scale_name} failed: {e}. Skipping this configuration.")
                if "out of memory" in str(e).lower():
                    print("      This is likely an Out Of Memory error. Try reducing batch_size or model dimensions for this scale.")
        
        self._analyze_scaling_trends(scaling_results_list)
        return scaling_results_list
    
    def _benchmark_single_config(self, model, test_input, config_name_str): # Renamed
        """Benchmark a single model configuration (baseline vs compiled)"""
        
        # Baseline measurement
        baseline_times_list = self._measure_baseline(model, test_input) # Renamed
        
        # Compiled measurement
        torch._dynamo.reset() # Clear cache before compiling
        
        compile_start_time = time.perf_counter()
        compiled_model = torch.compile(model) # Default mode
        # First inference to ensure compilation finishes
        with torch.no_grad():
            _ = compiled_model(test_input)
        if torch.cuda.is_available(): torch.cuda.synchronize()
        compilation_duration_ms = (time.perf_counter() - compile_start_time) * 1000
        
        compiled_times_list = self._measure_compiled(compiled_model, test_input) # Renamed
        
        stats = self._calculate_benchmark_stats(baseline_times_list, compiled_times_list, config_name_str)
        stats['compilation_ms'] = compilation_duration_ms # Add compilation time
        return stats
    
    def _benchmark_compiled_model(self, compiled_model, test_input, config_name_str): # Renamed
        """Benchmark an already compiled model (measures execution time only)"""
        
        # Just measure compiled performance
        compiled_times_list = self._measure_compiled(compiled_model, test_input) # Renamed
        
        # Basic stats for compiled execution
        mean_val = statistics.mean(compiled_times_list) * 1000
        std_val = statistics.stdev(compiled_times_list) * 1000 if len(compiled_times_list) > 1 else 0
        median_val = statistics.median(compiled_times_list) * 1000
        
        return {
            'config_name': config_name_str,
            'optimized_times_ms': [t * 1000 for t in compiled_times_list], # Store times in ms
            'optimized_mean_ms': mean_val,
            'optimized_std_ms': std_val,
            'optimized_median_ms': median_val,
        }
    
    def _measure_baseline(self, model_to_test, test_input_tensor): # Renamed
        """Measure baseline (uncompiled) performance"""
        
        model_to_test.eval() # Ensure eval mode
        times_list = [] # Renamed
        with torch.no_grad(): # Ensure no_grad for inference
            # Warmup
            for _ in range(self.warmup_trials):
                _ = model_to_test(test_input_tensor)
            if torch.cuda.is_available(): torch.cuda.synchronize() # Sync after warmup loop
            
            # Measurement
            for _ in range(self.num_trials):
                if torch.cuda.is_available(): torch.cuda.synchronize() # Sync before timing
                
                start_time = time.perf_counter()
                _ = model_to_test(test_input_tensor)
                
                if torch.cuda.is_available(): torch.cuda.synchronize() # Sync after operation
                
                times_list.append(time.perf_counter() - start_time)
        
        return times_list
    
    def _measure_compiled(self, compiled_model_instance, test_input_tensor): # Renamed
        """Measure compiled model performance (assumes compilation already happened or is part of first call)"""
        
        compiled_model_instance.eval() # Ensure eval mode
        times_list = [] # Renamed
        with torch.no_grad(): # Ensure no_grad for inference
            # First run (might include final parts of JIT, or just be a regular run if fully AOT compiled)
            _ = compiled_model_instance(test_input_tensor)
            if torch.cuda.is_available(): torch.cuda.synchronize()

            # Warmup (for compiled model)
            for _ in range(self.warmup_trials):
                _ = compiled_model_instance(test_input_tensor)
            if torch.cuda.is_available(): torch.cuda.synchronize() # Sync after warmup loop
            
            # Measurement
            for _ in range(self.num_trials):
                if torch.cuda.is_available(): torch.cuda.synchronize() # Sync before timing
                
                start_time = time.perf_counter()
                _ = compiled_model_instance(test_input_tensor)
                
                if torch.cuda.is_available(): torch.cuda.synchronize() # Sync after operation
                
                times_list.append(time.perf_counter() - start_time)
        
        return times_list
    
    def _calculate_benchmark_stats(self, baseline_times_list, compiled_times_list, config_name_str): # Renamed
        """Calculate comprehensive benchmark statistics"""
        
        baseline_mean = statistics.mean(baseline_times_list)
        baseline_std = statistics.stdev(baseline_times_list) if len(baseline_times_list) > 1 else 0
        
        compiled_mean = statistics.mean(compiled_times_list)
        compiled_std = statistics.stdev(compiled_times_list) if len(compiled_times_list) > 1 else 0
        
        speedup_factor = baseline_mean / compiled_mean if compiled_mean > 0 else float('inf') # Renamed
        
        return {
            'config_name': config_name_str,
            'baseline_mean_ms': baseline_mean * 1000,
            'baseline_std_ms': baseline_std * 1000,
            'baseline_times_ms': [t * 1000 for t in baseline_times_list],
            'optimized_mean_ms': compiled_mean * 1000,
            'optimized_std_ms': compiled_std * 1000,
            'optimized_times_ms': [t * 1000 for t in compiled_times_list],
            'speedup': speedup_factor,
            'improvement_pct': (speedup_factor - 1) * 100 if speedup_factor > 0 else (-float('inf') if speedup_factor == 0 else 0) # Handle no speedup or slowdown
        }
    
    def _print_benchmark_result(self, result_stats): # Renamed
        """Print formatted benchmark result"""
        print(f"   📊 Results for {result_stats['config_name']}:")
        print(f"      Baseline: {result_stats['baseline_mean_ms']:.3f} ± {result_stats['baseline_std_ms']:.3f} ms")
        print(f"      Optimized: {result_stats['optimized_mean_ms']:.3f} ± {result_stats['optimized_std_ms']:.3f} ms")
        if 'compilation_ms' in result_stats:
             print(f"      Compilation Time: {result_stats['compilation_ms']:.1f} ms")
        print(f"      Speedup: {result_stats['speedup']:.2f}x ({result_stats['improvement_pct']:.1f}% improvement)")
    
    def _analyze_complexity_trends(self, complexity_results_list): # Renamed
        """Analyze trends across model complexities"""
        print(f"\n📈 MODEL COMPLEXITY TRENDS ANALYSIS")
        print("-" * 55) # Adjusted width
        
        print(f"{'Model':<15} {'Speedup':<8} {'Improvement (%)':<18} {'Assessment':<15}") # Adjusted headers
        print("-" * 55)
        
        for result_stats in complexity_results_list: # Renamed
            speedup_val = result_stats['speedup'] # Renamed
            improvement_val = result_stats['improvement_pct'] # Renamed
            
            if speedup_val > 2.0: assessment_str = "🚀 Excellent" # Renamed
            elif speedup_val > 1.5: assessment_str = "✅ Good"
            elif speedup_val > 1.1: assessment_str = "⚡ Moderate"
            elif speedup_val > 0: assessment_str = "⚠️  Minimal"
            else: assessment_str = "❌ Slowdown"
            
            print(f"{result_stats['config_name']:<15} {speedup_val:<8.2f} {improvement_val:<18.1f} {assessment_str:<15}")
    
    def _analyze_mode_comparison(self, mode_results_list, baseline_mean_ms_for_comparison): # Renamed
        """Analyze compilation mode performance"""
        print(f"\n🎯 COMPILATION MODE COMPARISON ANALYSIS")
        print("-" * 70) # Adjusted width
        print(f"{'Mode':<18} {'Exec Time (ms)':<18} {'Compile Time (ms)':<20} {'Speedup vs Base':<15}")
        print("-" * 70)

        if not mode_results_list:
            print("   No mode results to analyze.")
            return

        best_mode_by_exec = min(mode_results_list, key=lambda x: x['optimized_mean_ms'])
        
        for result_stats in mode_results_list: # Renamed
            speedup_vs_baseline = baseline_mean_ms_for_comparison / result_stats['optimized_mean_ms'] if result_stats['optimized_mean_ms'] > 0 else float('inf')
            print(f"{result_stats['mode']:<18} {result_stats['optimized_mean_ms']:<18.3f} {result_stats.get('compilation_ms', 'N/A'):<20.1f} {speedup_vs_baseline:<15.2f}x")
            
        print(f"\n🏆 Best performing mode (by execution time): {best_mode_by_exec['mode']} ({best_mode_by_exec['optimized_mean_ms']:.3f}ms exec)")
    
    def _analyze_scaling_trends(self, scaling_results_list): # Renamed
        """Analyze input scaling trends"""
        print(f"\n📈 INPUT SCALING TRENDS ANALYSIS (Elements/ms)")
        print("-" * 50) # Adjusted width
        print(f"{'Scale Config (B,S,H)':<25} {'Elements/ms (K)':<20}")
        print("-" * 50)

        if not scaling_results_list:
            print("   No scaling results to analyze.")
            return

        for result_stats in scaling_results_list: # Renamed
            elements_per_ms = result_stats['total_elements'] / result_stats['optimized_mean_ms'] if result_stats['optimized_mean_ms'] > 0 else 0
            scale_cfg = result_stats['scale_config']
            cfg_str = f"B{scale_cfg['batch']}_S{scale_cfg['seq_len']}_H{scale_cfg['hidden_size']}"
            print(f"{cfg_str:<25} {elements_per_ms/1000:<20.1f}")
    
    # Model factories for different complexities
    # These now accept hidden_size as an argument, assuming seq_len is part of input_shape
    def _create_simple_model(self, hidden_size, input_seq_len=128): # Default seq_len if not from shape
        # Simple model: Linear -> ReLU -> Linear. Input: (Batch, SeqLen, HiddenIn)
        # For this example, let's assume hidden_size is the input feature size for the first linear layer.
        return nn.Sequential(
            nn.Linear(hidden_size, hidden_size), # Input features = hidden_size
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size)  # Output features = hidden_size
        )
    
    def _create_medium_model(self, hidden_size, input_seq_len=256):
        return nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Linear(hidden_size, hidden_size * 2), # Example: expand
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size * 2, hidden_size), # Example: contract
            nn.LayerNorm(hidden_size)
        )
    
    def _create_complex_model(self, hidden_size, input_seq_len=512):
        return nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Linear(hidden_size, hidden_size * 4),
            nn.GELU(),
            nn.Linear(hidden_size * 4, hidden_size * 4),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size * 4, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.GELU()
        )
    
    def _create_very_complex_model(self, hidden_size, input_seq_len=256): # Example: Transformer-like block
        # A more complex model with multiple layers, e.g., a few transformer blocks
        # This is a simplified example, not a full transformer block
        layers = []
        num_layers = 4 # Example: 4 "blocks"
        current_size = hidden_size
        for i in range(num_layers):
            intermediate_size = current_size * 4 # Feedforward expansion
            layers.extend([
                nn.LayerNorm(current_size),
                nn.Linear(current_size, intermediate_size),
                nn.GELU(),
                nn.Dropout(0.1),
                nn.Linear(intermediate_size, current_size),
                nn.Dropout(0.1) # Dropout after FFN
            ])
            # Add a residual connection concept if this were a real block
        return nn.Sequential(*layers)

# Execute comprehensive benchmarking
# Ensure 'device' is defined from a previous cell (e.g., setup cell)
# global device # If device is from global scope of a previous cell execution
if 'device' not in globals():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Warning: 'device' not found in global scope, re-initialized to {device}")

benchmark_suite_instance = AdvancedBenchmarkSuite(device=device) # Renamed

print("🚀 LAUNCHING COMPREHENSIVE BENCHMARK SUITE")
print("=" * 50)

# Run all benchmark categories
complexity_results_list = benchmark_suite_instance.benchmark_model_complexity() # Renamed
mode_results_list = benchmark_suite_instance.benchmark_compilation_modes() # Renamed
scaling_results_list = benchmark_suite_instance.benchmark_input_scaling() # Renamed

print(f"\n🎓 Comprehensive Benchmarking Complete!")
print(f"   📊 Use these results to guide optimization decisions.")
print(f"   🎯 Focus compilation efforts on models and configurations showing significant speedup (e.g., >1.5x).")
print(f"   ⚡ Consider input scaling behavior when designing production systems, especially for models sensitive to tensor sizes.")
print(f"   ⚙️  Evaluate different compilation modes; 'max-autotune' might offer better runtime but costs more compile time.")

🚀 LAUNCHING COMPREHENSIVE BENCHMARK SUITE
🧪 MODEL COMPLEXITY ANALYSIS

🔬 Testing: Simple Ops
   Model Input Features Shape (SeqLen, Hidden): (128, 256)
   Actual Tensor Shape (Batch, SeqLen, Hidden): (16, 128, 256)


/home/alibina/anaconda3/envs/pytorch-qat/lib/python3.12/site-packages/torch/_inductor/compile_fx.py:236: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
W0617 12:56:00.072000 260807 site-packages/torch/_inductor/utils.py:1250] [0/0] Not enough SMs to use max_autotune_gemm mode


   📊 Results for Simple Ops:
      Baseline: 2.739 ± 0.887 ms
      Optimized: 2.796 ± 0.470 ms
      Compilation Time: 838.1 ms
      Speedup: 0.98x (-2.0% improvement)

🔬 Testing: Medium Model
   Model Input Features Shape (SeqLen, Hidden): (256, 512)
   Actual Tensor Shape (Batch, SeqLen, Hidden): (16, 256, 512)
   📊 Results for Medium Model:
      Baseline: 29.050 ± 0.340 ms
      Optimized: 23.731 ± 0.289 ms
      Compilation Time: 970.8 ms
      Speedup: 1.22x (22.4% improvement)

🔬 Testing: Complex Model
   Model Input Features Shape (SeqLen, Hidden): (512, 1024)
   Actual Tensor Shape (Batch, SeqLen, Hidden): (16, 512, 1024)
   📊 Results for Medium Model:
      Baseline: 29.050 ± 0.340 ms
      Optimized: 23.731 ± 0.289 ms
      Compilation Time: 970.8 ms
      Speedup: 1.22x (22.4% improvement)

🔬 Testing: Complex Model
   Model Input Features Shape (SeqLen, Hidden): (512, 1024)
   Actual Tensor Shape (Batch, SeqLen, Hidden): (16, 512, 1024)
   📊 Results for Complex Model:
   

In [22]:
# 🔍 Debugging Compilation Issues: Common Problems and Solutions

def demonstrate_common_issues():
    """
    Show common compilation issues and how to debug and fix them
    """
    
    print("🐛 DEBUGGING COMPILATION ISSUES")
    print("=" * 45)
    
    # Issue 1: Graph Breaks from Dynamic Control Flow
    print("🔍 Issue 1: Graph Breaks from Python control flow dependent on tensor values")
    print("-" * 70) # Adjusted width
    
    # Ensure device is defined
    if 'device' not in globals():
        current_device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Warning: 'device' not found, using {current_device}")
    else:
        current_device = device


    # Problematic function: Python if statement on tensor data
    def problematic_function_graph_break(x):
        y = torch.relu(x)
        # This condition is evaluated at runtime based on tensor data - causes graph break
        if x.sum() > 0:  
            return y + 1.0
        else:
            return y - 1.0
    
    # Improved function: Use torch.where for conditional logic on tensors
    def improved_function_no_graph_break(x):
        y = torch.relu(x)
        # torch.where is traceable and avoids graph break for this pattern
        condition = x.sum() > 0 
        return torch.where(condition, y + 1.0, y - 1.0)
    
    test_input_graph_break = torch.randn(100, device=current_device)
    
    print("   Testing function prone to graph breaks (Python if on tensor data):")
    print("   Expect warnings about graph breaks if TORCH_LOGS includes 'graph_breaks' or similar verbosity.")
    
    try:
        # Enable graph break logging if not already on (for this specific test)
        original_torch_logs = os.environ.get("TORCH_LOGS")
        os.environ["TORCH_LOGS"] = str(original_torch_logs or "") + ",graph_breaks" 
        torch._dynamo.reset() # Reset to apply new env var

        compiled_problematic = torch.compile(problematic_function_graph_break)
        result1 = compiled_problematic(test_input_graph_break)
        print("   ✅ Problematic function compiled. Check logs for graph break warnings.")
        
        torch._dynamo.reset() # Reset for the next compilation
        compiled_improved = torch.compile(improved_function_no_graph_break)
        result2 = compiled_improved(test_input_graph_break)
        print("   ✅ Improved version (with torch.where) compiled. Should have fewer/no graph breaks for this case.")

        # Restore TORCH_LOGS
        if original_torch_logs is None:
            del os.environ["TORCH_LOGS"]
        else:
            os.environ["TORCH_LOGS"] = original_torch_logs
        torch._dynamo.reset()

    except Exception as e:
        print(f"   ❌ Compilation issue during graph break demo: {e}")
    
    # Issue 2: Dynamic Shapes
    print(f"\n🔍 Issue 2: Handling Dynamic Shapes in Compiled Functions")
    print("-" * 70)
    
    # Function whose behavior might implicitly depend on shape details not just rank/dtype
    def shape_sensitive_function_reshape(x):
        # Example: reshape that might be problematic if not specialized or dynamic=True
        return x.view(x.shape[0], -1).mean(dim=0) # Flatten all but batch
    
    shapes_to_test_dynamic = [
        (10, 20, 5), 
        (15, 30, 3),   
        (20, 10, 8), 
    ]
    
    print("   Testing with different input shapes (fixed rank, varying dimensions):")
    
    print("\n   Attempt 1: Default compilation (dynamic=False implicitly)")
    try:
        torch._dynamo.reset()
        # Default compilation might lead to recompilations or errors if shapes vary too much
        compiled_static_shapes = torch.compile(shape_sensitive_function_reshape) 
        
        for i, shape_dims in enumerate(shapes_to_test_dynamic):
            test_tensor_dyn = torch.randn(shape_dims, device=current_device)
            print(f"      Running with shape {test_tensor_dyn.shape}...")
            _ = compiled_static_shapes(test_tensor_dyn)
            print(f"      ✅ Shape {test_tensor_dyn.shape}: Success (may have recompiled if specialization occurred)")
        print("   ✅ Default compilation handled multiple shapes (possibly via recompilation/specialization).")
        
    except Exception as e:
        print(f"   ⚠️  Default compilation issue with varying shapes: {e}")
    
    print("\n   Attempt 2: Compiling with dynamic=True")
    try:
        torch._dynamo.reset()
        compiled_dynamic_shapes = torch.compile(shape_sensitive_function_reshape, dynamic=True)
        
        for i, shape_dims in enumerate(shapes_to_test_dynamic):
            test_tensor_dyn = torch.randn(shape_dims, device=current_device)
            print(f"      Running with shape {test_tensor_dyn.shape} (dynamic=True)...")
            _ = compiled_dynamic_shapes(test_tensor_dyn)
            print(f"      ✅ Dynamic (dynamic=True) shape {test_tensor_dyn.shape}: Success")
        print("   ✅ `dynamic=True` compilation successful with varying shapes, likely avoiding recompilations.")

    except Exception as e2:
        print(f"   ❌ Still failing with dynamic=True: {e2}")
    
    # Issue 3: Performance Regression Detection for very simple operations
    print(f"\n🔍 Issue 3: Performance Regression for Trivial Operations")
    print("-" * 70)
    
    def very_simple_operation(x):
        # Extremely simple operation that might not benefit from compilation overhead
        return x + 1.0
    
    test_tensor_simple_op = torch.randn(1000, 1000, device=current_device) # Larger tensor
    
    print(f"   Measuring baseline for very_simple_operation on shape {test_tensor_simple_op.shape}...")
    baseline_times_simple = []
    for _ in range(10): # Fewer iterations for quick demo
        if torch.cuda.is_available(): torch.cuda.synchronize()
        start_time = time.perf_counter()
        _ = very_simple_operation(test_tensor_simple_op)
        if torch.cuda.is_available(): torch.cuda.synchronize()
        baseline_times_simple.append(time.perf_counter() - start_time)
    baseline_avg_simple = statistics.mean(baseline_times_simple)
    
    print(f"   Measuring compiled version for very_simple_operation...")
    torch._dynamo.reset()
    compiled_very_simple = torch.compile(very_simple_operation)
    
    # Warmup and first run (includes compilation time)
    _ = compiled_very_simple(test_tensor_simple_op) 
    if torch.cuda.is_available(): torch.cuda.synchronize()

    compiled_times_simple = []
    for _ in range(10):
        if torch.cuda.is_available(): torch.cuda.synchronize()
        start_time = time.perf_counter()
        _ = compiled_very_simple(test_tensor_simple_op)
        if torch.cuda.is_available(): torch.cuda.synchronize()
        compiled_times_simple.append(time.perf_counter() - start_time)
    compiled_avg_simple = statistics.mean(compiled_times_simple)
    
    print(f"   Baseline (simple op): {baseline_avg_simple*1000:.4f} ms")
    print(f"   Compiled (simple op): {compiled_avg_simple*1000:.4f} ms")
    
    # Regression if compiled is, e.g., 5% slower (allowing for noise)
    if compiled_avg_simple > baseline_avg_simple * 1.05:  
        print("   ⚠️  Performance regression detected for trivial operation!")
        print("      The overhead of compilation and calling the compiled kernel")
        print("      exceeds the benefit for this very simple operation.")
        print("   💡 Recommendations:")
        print("      • Avoid compiling extremely simple, non-bottleneck functions.")
        print("      • Profile to identify true bottlenecks before applying torch.compile broadly.")
    elif compiled_avg_simple < baseline_avg_simple:
        speedup_simple = baseline_avg_simple / compiled_avg_simple
        print(f"   ✅ Performance improved or similar: {speedup_simple:.2f}x speedup for simple op.")
    else:
        print(f"   ℹ️  Compiled performance is similar to baseline for this simple op.")


# Run debugging demonstration
demonstrate_common_issues()

print(f"\n🎓 Debugging Best Practices Summary:")
print(f"   ✅ Be mindful of Python control flow on tensor data; use `torch.where` or refactor for traceability.")
print(f"   ✅ Use `dynamic=True` or input specialization when dealing with variable input shapes if recompilation is an issue.")  
print(f"   ✅ Profile! Not all operations benefit from compilation; overhead can exceed gains for trivial ops.")
print(f"   ✅ Utilize environment variables like `TORCH_LOGS` for detailed insights during debugging.")
print(f"   ✅ Start with simple, isolated examples when debugging, then gradually add complexity.")

🐛 DEBUGGING COMPILATION ISSUES
🔍 Issue 1: Graph Breaks from Python control flow dependent on tensor values
----------------------------------------------------------------------
   Testing function prone to graph breaks (Python if on tensor data):
   Expect warnings about graph breaks if TORCH_LOGS includes 'graph_breaks' or similar verbosity.
   ✅ Problematic function compiled. Check logs for graph break warnings.
   ✅ Problematic function compiled. Check logs for graph break warnings.
   ✅ Improved version (with torch.where) compiled. Should have fewer/no graph breaks for this case.

🔍 Issue 2: Handling Dynamic Shapes in Compiled Functions
----------------------------------------------------------------------
   Testing with different input shapes (fixed rank, varying dimensions):

   Attempt 1: Default compilation (dynamic=False implicitly)
      Running with shape torch.Size([10, 20, 5])...
   ✅ Improved version (with torch.where) compiled. Should have fewer/no graph breaks for thi

## Debugging Common Compilation Issues

Even with PyTorch's sophisticated compilation system, issues can arise. Let's explore common problems and their solutions.

### 🐛 Common Issues and Solutions

#### 1. **Compilation Failures**
```python
# Common error: Dynamic shapes
RuntimeError: Cannot compile with dynamic shapes

# Solution: Use torch.compile with dynamic=True or fix shapes
compiled_fn = torch.compile(fn, dynamic=True)
```

#### 2. **Performance Regressions**
```python
# Issue: Compiled version slower than baseline
# Causes: Small models, wrong compilation mode, graph breaks

# Solutions:
# 1. Try different modes
compiled_fn = torch.compile(fn, mode="reduce-overhead")  # vs "default"

# 2. Check for graph breaks
with torch._dynamo.optimize("inductor"):
    result = fn(input)  # Will show graph break warnings
```

#### 3. **Memory Issues**
```python
# Issue: Out of memory during compilation
# Solution: Reduce compilation scope or use checkpointing
@torch.compile(mode="reduce-overhead")
def smaller_function(x):
    # Break large functions into smaller ones
    return partial_computation(x)
```

#### 4. **Unsupported Operations**
```python
# Issue: Some operations don't support compilation
# Solution: Selective compilation or fallbacks

class HybridModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.compiled_part = torch.compile(self.core_computation)
        
    def forward(self, x):
        # Compiled part
        x = self.compiled_part(x)
        
        # Unsupported operations run normally
        x = unsupported_operation(x)
        
        return x
```

### 🔧 Debugging Toolkit

1. **Environment Variables**: Use detailed logging
2. **Graph Breaks**: Monitor for optimization barriers
3. **Profiling**: Use torch.profiler for detailed analysis
4. **Selective Compilation**: Isolate problematic areas

## 🎯 Recommended Jupyter Debugging Methodology

Based on our comprehensive analysis, here's the **optimal debugging workflow** for PyTorch `torch.compile()` in Jupyter environments:

### **Primary Debugging Strategy: Two-Method Approach**

#### **Method 1: Dynamo Analysis** 📊 
**Use for:** Quick issue identification and production debugging
- ✅ **Native Jupyter operation** - no external processes required
- ✅ **Structured output** - programmatic access to compilation data  
- ✅ **Fast execution** - immediate insights without compilation overhead
- ✅ **Actionable information** - directly identifies graph breaks and optimization barriers

```python
# Quick debugging workflow
explanations = torch._dynamo.explain(your_model)(test_input)
# Instantly see graph breaks, operation counts, and optimization potential
```

#### **Method 2: Subprocess Capture** 🔍
**Use for:** Deep learning and environment variable exploration
- ✅ **Complete visibility** - captures all PyTorch logs that Jupyter normally can't see
- ✅ **Environment variable effects** - shows the impact of TORCH_LOGS, debug settings
- ✅ **Educational value** - perfect for understanding compilation internals
- ✅ **Comprehensive output** - access to detailed compilation pipeline information

```python
# Deep investigation workflow  
debug_success = demonstrate_jupyter_vs_terminal_logging()
# Captures external PyTorch logs for complete compilation visibility
```

### **Why This Two-Method Approach Is Superior**

**🚀 Efficiency**: Start with Dynamo Analysis for 90% of debugging needs
**🔬 Depth**: Use Subprocess Capture when you need complete compilation visibility  
**🎯 Practicality**: Both methods work reliably in Jupyter environments
**💡 Complementary**: Quick analysis + deep investigation = complete debugging coverage

### **When to Use Each Method**

| Scenario | Recommended Method | Why |
|----------|-------------------|-----|
| **Production debugging** | Dynamo Analysis | Fast, programmatic, native Jupyter |
| **Learning PyTorch compilation** | Subprocess Capture | Complete visibility into internal processes |
| **Graph break troubleshooting** | Dynamo Analysis | Direct identification of breaks |
| **Environment variable testing** | Subprocess Capture | Shows actual log output effects |
| **Automated analysis** | Dynamo Analysis | Structured, programmable output |
| **Understanding kernel generation** | Subprocess Capture | Reveals Triton code generation process |

This methodology provides complete debugging coverage while maximizing efficiency and maintaining the interactive benefits of Jupyter development.

## Summary: Advanced Debugging & Optimization Mastered

Excellent work! You've now mastered advanced debugging techniques and optimization strategies for PyTorch's `torch.compile()` system. Let's recap your newly acquired expert-level skills:

### **Advanced Skills Mastered**

#### **🔍 Expert-Level Debugging**
- **Jupyter-Focused Debugging**: Mastered the two most effective debugging methods for Jupyter environments
- **Subprocess Capture**: External process execution to capture PyTorch logs that Jupyter can't see
- **Dynamo Analysis**: Programmatic analysis of compilation graphs and optimization decisions  
- **Artifact Inspection**: Understanding and analyzing generated Triton kernels and debug files

#### **⚡ Performance Engineering**
- **Statistical Benchmarking**: Rigorous performance measurement techniques
- **Break-even Analysis**: Economic modeling for compilation decisions
- **Scaling Analysis**: Understanding performance across different model sizes
- **Mode Comparison**: Choosing optimal compilation strategies

#### **🎯 Optimization Strategies**
- **Systematic Analysis**: Framework for evaluating compilation benefits
- **Pattern Recognition**: Identifying operations that benefit from compilation
- **Selective Compilation**: Strategic application for maximum benefit
- **Production Considerations**: Real-world deployment strategies

### **Expert Techniques Acquired**

1. **✅ Jupyter-Native Debugging**: Two-method approach optimized for notebook environments
2. **✅ Kernel Exploration**: Understanding and analyzing generated Triton code
3. **✅ Performance Benchmarking**: Statistical measurement and analysis
4. **✅ Issue Resolution**: Common problems and systematic solutions

### **Preferred Jupyter Debugging Workflow**

**Primary Methods for Jupyter Development:**

1. **🔍 Subprocess Capture**: Capture PyTorch logs by running compilation externally
   - ✅ Shows all PyTorch debug output that Jupyter normally can't display
   - ✅ Perfect for understanding environment variable effects
   - ✅ Ideal for learning and detailed investigation

2. **📊 Dynamo Analysis**: Use `torch._dynamo.explain()` for programmatic insights
   - ✅ Always works natively in Jupyter
   - ✅ Structured, actionable data about graph breaks and optimization
   - ✅ Fast execution without external processes
   - ✅ Perfect for automated analysis and production debugging

### **What You Can Now Do**

- **Debug Complex Compilation Issues**: Two-method systematic approach to troubleshooting
- **Analyze Generated Kernels**: Understanding optimization patterns in Triton code
- **Measure Performance Scientifically**: Statistical rigor in benchmarking
- **Make Informed Decisions**: Data-driven compilation strategies

### **What's Next in Part 3?**

Now that you're an expert in debugging and optimization, Part 3 will cover:

#### **Part 3: Production Deployment & Best Practices** *(Final Part)*
- **Enterprise Deployment Patterns**: Production-ready strategies
- **Advanced Troubleshooting**: Expert problem-solving techniques  
- **Performance Monitoring**: Real-time optimization tracking
- **Best Practices**: Professional recommendations and patterns

### 💡 **Apply Your Advanced Skills**

**Expert Challenge**: Take a complex PyTorch model from your work and apply the full debugging and optimization pipeline you've learned. Use the two-method debugging approach and benchmarking framework to make data-driven decisions about compilation strategy!

---

## 🔗 **Continue to Final Part**

Ready for production deployment? Continue with **Part 3: Production Deployment & Best Practices** where we'll cover:

- Enterprise-grade deployment strategies
- Advanced troubleshooting techniques
- Production monitoring and alerting
- Expert best practices and patterns

**You're now a torch.compile() optimization expert! 🚀**